// <auto-generated/>
namespace Jellyfin.Client.Models
{
	/// <summary>
	/// An entity representing a user&apos;s access schedule.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccessSchedule
    {
        /// <summary>Gets or sets the day of week.</summary>
        public global::Jellyfin.Client.Models.AccessSchedule_DayOfWeek? DayOfWeek { get; set; }
        /// <summary>Gets or sets the end hour.</summary>
        public double? EndHour { get; set; }
        /// <summary>Gets the id of this instance.</summary>
        public int? Id { get; private set; }
        /// <summary>Gets or sets the start hour.</summary>
        public double? StartHour { get; set; }
        /// <summary>Gets the id of the associated user.</summary>
        public Guid? UserId { get; set; }
    }
}
