// <auto-generated/>
using System.Text.Json.Serialization;
namespace Jellyfin.Client.Models
{
	/// <summary>Gets or sets the day of week.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
	[JsonConverter(typeof(JsonStringEnumConverter<AccessSchedule_DayOfWeek>))]
	public enum AccessSchedule_DayOfWeek
    {
        [JsonStringEnumMemberName("Sunday")]
        Sunday,

        [JsonStringEnumMemberName("Monday")]
        Monday,

        [JsonStringEnumMemberName("Tuesday")]
        Tuesday,
        
		[JsonStringEnumMemberName("Wednesday")]
        Wednesday,
        
		[JsonStringEnumMemberName("Thursday")]
		Thursday,
        
		[JsonStringEnumMemberName("Friday")]
        Friday,
        
		[JsonStringEnumMemberName("Saturday")]
        Saturday,
        
		[JsonStringEnumMemberName("Everyday")]
        Everyday,
        
		[JsonStringEnumMemberName("Weekday")]
        Weekday,
        
		[JsonStringEnumMemberName("Weekend")]
        Weekend,
    }
}
