// <auto-generated/>
#pragma warning disable CS0618
namespace Jellyfin.Client.Models
{
	/// <summary>
	/// An activity log entry.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActivityLogEntry
    {
        /// <summary>Gets or sets the date.</summary>
        public DateTimeOffset? Date { get; set; }
        /// <summary>Gets or sets the identifier.</summary>
        public long? Id { get; set; }
        /// <summary>Gets or sets the item identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ItemId { get; set; }
#nullable restore
#else
        public string ItemId { get; set; }
#endif
        /// <summary>Gets or sets the name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Gets or sets the overview.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Overview { get; set; }
#nullable restore
#else
        public string Overview { get; set; }
#endif

		[JsonConverter(typeof(JsonStringEnumConverter<ActivityLogEntry_Severity>))]
		/// <summary>Gets or sets the log severity.</summary>
		public global::Jellyfin.Client.Models.ActivityLogEntry_Severity? Severity { get; set; }
        /// <summary>Gets or sets the short overview.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShortOverview { get; set; }
#nullable restore
#else
        public string ShortOverview { get; set; }
#endif
        /// <summary>Gets or sets the type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>Gets or sets the user identifier.</summary>
        public Guid? UserId { get; set; }
        /// <summary>Gets or sets the user primary image tag.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserPrimaryImageTag { get; set; }
#nullable restore
#else
        public string UserPrimaryImageTag { get; set; }
#endif

    }
}
#pragma warning restore CS0618
