// <auto-generated/>
using System.Text.Json.Serialization;
namespace Jellyfin.Client.Models
{
	/// <summary>Gets or sets the log severity.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ActivityLogEntry_Severity
    {
        [JsonStringEnumMemberName("Trace")]

        Trace,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Debug")]

        Debug,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Information")]

        Information,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Warning")]

        Warning,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Error")]

        Error,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Critical")]

        Critical,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("None")]

        None,
        #pragma warning restore CS1591
    }
}
