// <auto-generated/>
#pragma warning disable CS0618
namespace Jellyfin.Client.Models
{
	/// <summary>
	/// Add virtual folder dto.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AddVirtualFolderDto
    {
        /// <summary>Gets or sets library options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.LibraryOptions? LibraryOptions { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.LibraryOptions LibraryOptions { get; set; }
#endif
    }
}
#pragma warning restore CS0618
