// <auto-generated/>
#pragma warning disable CS0618
namespace Jellyfin.Client.Models
{
	[global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AlbumInfoRemoteSearchQuery
    #pragma warning restore CS1591
    {
        /// <summary>Gets or sets a value indicating whether disabled providers should be included.</summary>
        public bool? IncludeDisabledProviders { get; set; }
        /// <summary>The ItemId property</summary>
        public Guid? ItemId { get; set; }
        /// <summary>The SearchInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.AlbumInfo? SearchInfo { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.AlbumInfo SearchInfo { get; set; }
#endif
        /// <summary>Gets or sets the provider name to search within if set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SearchProviderName { get; set; }
#nullable restore
#else
        public string SearchProviderName { get; set; }
#endif
    }
}
#pragma warning restore CS0618
