// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Gets or sets the artist provider ids.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AlbumInfo_ArtistProviderIds 
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Jellyfin.Client.Models.AlbumInfo_ArtistProviderIds"/> and sets the default values.
        /// </summary>
        public AlbumInfo_ArtistProviderIds()
        {
            AdditionalData = new Dictionary<string, object>();
        }
    }
}
#pragma warning restore CS0618
