// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AllThemeMediaResult 
    #pragma warning restore CS1591
    {
        /// <summary>Class ThemeMediaResult.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.ThemeMediaResult? SoundtrackSongsResult { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.ThemeMediaResult SoundtrackSongsResult { get; set; }
#endif
        /// <summary>Class ThemeMediaResult.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.ThemeMediaResult? ThemeSongsResult { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.ThemeMediaResult ThemeSongsResult { get; set; }
#endif
        /// <summary>Class ThemeMediaResult.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.ThemeMediaResult? ThemeVideosResult { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.ThemeMediaResult ThemeVideosResult { get; set; }
#endif
    }
}
#pragma warning restore CS0618
