// <auto-generated/>
namespace Jellyfin.Client.Models
{
	/// <summary>Gets or sets the audio.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BaseItemDto_Audio
    {
        [JsonStringEnumMemberName("Mono")]

        Mono,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Stereo")]

        Stereo,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Dolby")]

        Dolby,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("DolbyDigital")]

        DolbyDigital,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Thx")]

        Thx,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Atmos")]

        Atmos,
        #pragma warning restore CS1591
    }
}
