// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BaseItemPerson_ImageBlurHashes_BoxRear 
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_BoxRear"/> and sets the default values.
        /// </summary>
        public BaseItemPerson_ImageBlurHashes_BoxRear()
        {
            AdditionalData = new Dictionary<string, object>();
        }
    }
}
#pragma warning restore CS0618
