// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>The person kind.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BaseItemPerson_Type
    {
        [JsonStringEnumMemberName("Unknown")]

        Unknown,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Actor")]

        Actor,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Director")]

        Director,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Composer")]

        Composer,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Writer")]

        Writer,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("GuestStar")]

        GuestStar,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Producer")]

        Producer,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Conductor")]

        Conductor,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Lyricist")]

        Lyricist,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Arranger")]

        Arranger,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Engineer")]

        Engineer,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Mixer")]

        Mixer,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Remixer")]

        Remixer,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Creator")]

        Creator,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Artist")]

        Artist,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("AlbumArtist")]

        AlbumArtist,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Author")]

        Author,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Illustrator")]

        Illustrator,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Penciller")]

        Penciller,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Inker")]

        Inker,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Colorist")]

        Colorist,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Letterer")]

        Letterer,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("CoverArtist")]

        CoverArtist,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Editor")]

        Editor,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Translator")]

        Translator,
        #pragma warning restore CS1591
    }
}
