// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// This is used by the api to get information about a Person within a BaseItem.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BaseItemPerson 
    {
        /// <summary>Gets or sets the identifier.</summary>
        public Guid? Id { get; set; }
        /// <summary>Gets or sets the primary image blurhash.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes? ImageBlurHashes { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes ImageBlurHashes { get; set; }
#endif
        /// <summary>Gets or sets the name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Gets or sets the primary image tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrimaryImageTag { get; set; }
#nullable restore
#else
        public string PrimaryImageTag { get; set; }
#endif
        /// <summary>Gets or sets the role.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Role { get; set; }
#nullable restore
#else
        public string Role { get; set; }
#endif

		[JsonConverter(typeof(JsonStringEnumConverter<BaseItemPerson_Type>))]
		/// <summary>The person kind.</summary>
		public global::Jellyfin.Client.Models.BaseItemPerson_Type? Type { get; set; }
    }
}
#pragma warning restore CS0618
