// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BaseItemDto_ImageBlurHashes_Box 
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Jellyfin.Client.Models.BaseItemDto_ImageBlurHashes_Box"/> and sets the default values.
        /// </summary>
        public BaseItemDto_ImageBlurHashes_Box()
        {
            AdditionalData = new Dictionary<string, object>();
        }
    }
}
#pragma warning restore CS0618
