// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Gets or sets the primary image blurhash.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BaseItemPerson_ImageBlurHashes 
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The Art property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Art? Art { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Art Art { get; set; }
#endif
        /// <summary>The Backdrop property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Backdrop? Backdrop { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Backdrop Backdrop { get; set; }
#endif
        /// <summary>The Banner property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Banner? Banner { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Banner Banner { get; set; }
#endif
        /// <summary>The Box property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Box? Box { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Box Box { get; set; }
#endif
        /// <summary>The BoxRear property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_BoxRear? BoxRear { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_BoxRear BoxRear { get; set; }
#endif
        /// <summary>The Chapter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Chapter? Chapter { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Chapter Chapter { get; set; }
#endif
        /// <summary>The Disc property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Disc? Disc { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Disc Disc { get; set; }
#endif
        /// <summary>The Logo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Logo? Logo { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Logo Logo { get; set; }
#endif
        /// <summary>The Menu property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Menu? Menu { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Menu Menu { get; set; }
#endif
        /// <summary>The Primary property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Primary? Primary { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Primary Primary { get; set; }
#endif
        /// <summary>The Profile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Profile? Profile { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Profile Profile { get; set; }
#endif
        /// <summary>The Screenshot property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Screenshot? Screenshot { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Screenshot Screenshot { get; set; }
#endif
        /// <summary>The Thumb property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Thumb? Thumb { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes_Thumb Thumb { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Jellyfin.Client.Models.BaseItemPerson_ImageBlurHashes"/> and sets the default values.
        /// </summary>
        public BaseItemPerson_ImageBlurHashes()
        {
            AdditionalData = new Dictionary<string, object>();
        }
    }
}
#pragma warning restore CS0618
