// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the type of the iso.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BaseItemDto_IsoType
    {
        [JsonStringEnumMemberName("Dvd")]

        Dvd,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("BluRay")]

        BluRay,
        #pragma warning restore CS1591
    }
}
