// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// This is strictly used as a data transfer object from the api layer.This holds information about a BaseItem in a format that is convenient for the client.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BaseItemDto 
    {
        /// <summary>Gets or sets the air days.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.DayOfWeekObject?>? AirDays { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.DayOfWeekObject?> AirDays { get; set; }
#endif
        /// <summary>The AirsAfterSeasonNumber property</summary>
        public int? AirsAfterSeasonNumber { get; set; }
        /// <summary>The AirsBeforeEpisodeNumber property</summary>
        public int? AirsBeforeEpisodeNumber { get; set; }
        /// <summary>The AirsBeforeSeasonNumber property</summary>
        public int? AirsBeforeSeasonNumber { get; set; }
        /// <summary>Gets or sets the air time.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AirTime { get; set; }
#nullable restore
#else
        public string AirTime { get; set; }
#endif
        /// <summary>Gets or sets the album.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Album { get; set; }
#nullable restore
#else
        public string Album { get; set; }
#endif
        /// <summary>Gets or sets the album artist.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlbumArtist { get; set; }
#nullable restore
#else
        public string AlbumArtist { get; set; }
#endif
        /// <summary>Gets or sets the album artists.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.NameGuidPair>? AlbumArtists { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.NameGuidPair> AlbumArtists { get; set; }
#endif
        /// <summary>Gets or sets the album count.</summary>
        public int? AlbumCount { get; set; }
        /// <summary>Gets or sets the album id.</summary>
        public Guid? AlbumId { get; set; }
        /// <summary>Gets or sets the album image tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlbumPrimaryImageTag { get; set; }
#nullable restore
#else
        public string AlbumPrimaryImageTag { get; set; }
#endif
        /// <summary>The Altitude property</summary>
        public double? Altitude { get; set; }
        /// <summary>The Aperture property</summary>
        public double? Aperture { get; set; }
        /// <summary>The ArtistCount property</summary>
        public int? ArtistCount { get; set; }
        /// <summary>Gets or sets the artist items.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.NameGuidPair>? ArtistItems { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.NameGuidPair> ArtistItems { get; set; }
#endif
        /// <summary>Gets or sets the artists.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Artists { get; set; }
#nullable restore
#else
        public List<string> Artists { get; set; }
#endif
        /// <summary>Gets or sets the aspect ratio.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AspectRatio { get; set; }
#nullable restore
#else
        public string AspectRatio { get; set; }
#endif

		[JsonConverter(typeof(JsonStringEnumConverter<BaseItemDto_Audio>))]
		/// <summary>Gets or sets the audio.</summary>
		public global::Jellyfin.Client.Models.BaseItemDto_Audio? Audio { get; set; }
        /// <summary>Gets or sets the backdrop image tags.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? BackdropImageTags { get; set; }
#nullable restore
#else
        public List<string> BackdropImageTags { get; set; }
#endif
        /// <summary>The CameraMake property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CameraMake { get; set; }
#nullable restore
#else
        public string CameraMake { get; set; }
#endif
        /// <summary>The CameraModel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CameraModel { get; set; }
#nullable restore
#else
        public string CameraModel { get; set; }
#endif
        /// <summary>The CanDelete property</summary>
        public bool? CanDelete { get; set; }
        /// <summary>The CanDownload property</summary>
        public bool? CanDownload { get; set; }
        /// <summary>Gets or sets the channel identifier.</summary>
        public Guid? ChannelId { get; set; }
        /// <summary>The ChannelName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChannelName { get; set; }
#nullable restore
#else
        public string ChannelName { get; set; }
#endif
        /// <summary>The ChannelNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChannelNumber { get; set; }
#nullable restore
#else
        public string ChannelNumber { get; set; }
#endif
        /// <summary>Gets or sets the channel primary image tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChannelPrimaryImageTag { get; set; }
#nullable restore
#else
        public string ChannelPrimaryImageTag { get; set; }
#endif

		[JsonConverter(typeof(JsonStringEnumConverter<BaseItemDto_ChannelType>))]
		/// <summary>Gets or sets the type of the channel.</summary>
		public global::Jellyfin.Client.Models.BaseItemDto_ChannelType? ChannelType { get; set; }
        /// <summary>Gets or sets the chapters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.ChapterInfo>? Chapters { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.ChapterInfo> Chapters { get; set; }
#endif
        /// <summary>Gets or sets the child count.</summary>
        public int? ChildCount { get; set; }

		[JsonConverter(typeof(JsonStringEnumConverter<BaseItemDto_CollectionType>))]
		/// <summary>Gets or sets the type of the collection.</summary>
		public global::Jellyfin.Client.Models.BaseItemDto_CollectionType? CollectionType { get; set; }
        /// <summary>Gets or sets the community rating.</summary>
        public float? CommunityRating { get; set; }
        /// <summary>Gets or sets the completion percentage.</summary>
        public double? CompletionPercentage { get; set; }
        /// <summary>The Container property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Container { get; set; }
#nullable restore
#else
        public string Container { get; set; }
#endif
        /// <summary>Gets or sets the critic rating.</summary>
        public float? CriticRating { get; set; }
        /// <summary>Gets or sets the cumulative run time ticks.</summary>
        public long? CumulativeRunTimeTicks { get; set; }
        /// <summary>Gets or sets the current program.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemDto? CurrentProgram { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemDto CurrentProgram { get; set; }
#endif
        /// <summary>Gets or sets the custom rating.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomRating { get; set; }
#nullable restore
#else
        public string CustomRating { get; set; }
#endif
        /// <summary>Gets or sets the date created.</summary>
        public DateTimeOffset? DateCreated { get; set; }
        /// <summary>The DateLastMediaAdded property</summary>
        public DateTimeOffset? DateLastMediaAdded { get; set; }
        /// <summary>Gets or sets the display order.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayOrder { get; set; }
#nullable restore
#else
        public string DisplayOrder { get; set; }
#endif
        /// <summary>Gets or sets the display preferences id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayPreferencesId { get; set; }
#nullable restore
#else
        public string DisplayPreferencesId { get; set; }
#endif
        /// <summary>The EnableMediaSourceDisplay property</summary>
        public bool? EnableMediaSourceDisplay { get; set; }
        /// <summary>Gets or sets the end date.</summary>
        public DateTimeOffset? EndDate { get; set; }
        /// <summary>Gets or sets the episode count.</summary>
        public int? EpisodeCount { get; set; }
        /// <summary>Gets or sets the episode title.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EpisodeTitle { get; set; }
#nullable restore
#else
        public string EpisodeTitle { get; set; }
#endif
        /// <summary>Gets or sets the etag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Etag { get; set; }
#nullable restore
#else
        public string Etag { get; set; }
#endif
        /// <summary>The ExposureTime property</summary>
        public double? ExposureTime { get; set; }
        /// <summary>Gets or sets the external urls.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.ExternalUrl>? ExternalUrls { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.ExternalUrl> ExternalUrls { get; set; }
#endif

		[JsonConverter(typeof(JsonStringEnumConverter<BaseItemDto_ExtraType>))]
		/// <summary>The ExtraType property</summary>
		public global::Jellyfin.Client.Models.BaseItemDto_ExtraType? ExtraType { get; set; }
        /// <summary>The FocalLength property</summary>
        public double? FocalLength { get; set; }
        /// <summary>The ForcedSortName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ForcedSortName { get; set; }
#nullable restore
#else
        public string ForcedSortName { get; set; }
#endif
        /// <summary>The GenreItems property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.NameGuidPair>? GenreItems { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.NameGuidPair> GenreItems { get; set; }
#endif
        /// <summary>Gets or sets the genres.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Genres { get; set; }
#nullable restore
#else
        public List<string> Genres { get; set; }
#endif
        /// <summary>The HasLyrics property</summary>
        public bool? HasLyrics { get; set; }
        /// <summary>The HasSubtitles property</summary>
        public bool? HasSubtitles { get; set; }
        /// <summary>The Height property</summary>
        public int? Height { get; set; }
        /// <summary>Gets or sets the id.</summary>
        public Guid? Id { get; set; }
        /// <summary>Gets or sets the blurhashes for the image tags.Maps image type to dictionary mapping image tag to blurhash value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemDto_ImageBlurHashes? ImageBlurHashes { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemDto_ImageBlurHashes ImageBlurHashes { get; set; }
#endif

		[JsonConverter(typeof(JsonStringEnumConverter<BaseItemDto_ImageOrientation>))]
		/// <summary>The ImageOrientation property</summary>
		public global::Jellyfin.Client.Models.BaseItemDto_ImageOrientation? ImageOrientation { get; set; }
        /// <summary>Gets or sets the image tags.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemDto_ImageTags? ImageTags { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemDto_ImageTags ImageTags { get; set; }
#endif
        /// <summary>Gets or sets the index number.</summary>
        public int? IndexNumber { get; set; }
        /// <summary>Gets or sets the index number end.</summary>
        public int? IndexNumberEnd { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is folder.</summary>
        public bool? IsFolder { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is HD.</summary>
        public bool? IsHD { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is kids.</summary>
        public bool? IsKids { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is live.</summary>
        public bool? IsLive { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is movie.</summary>
        public bool? IsMovie { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is news.</summary>
        public bool? IsNews { get; set; }
        /// <summary>The IsoSpeedRating property</summary>
        public int? IsoSpeedRating { get; set; }

		[JsonConverter(typeof(JsonStringEnumConverter<BaseItemDto_IsoType>))]
		/// <summary>Gets or sets the type of the iso.</summary>
		public global::Jellyfin.Client.Models.BaseItemDto_IsoType? IsoType { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is place holder.</summary>
        public bool? IsPlaceHolder { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is premiere.</summary>
        public bool? IsPremiere { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is repeat.</summary>
        public bool? IsRepeat { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is series.</summary>
        public bool? IsSeries { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is sports.</summary>
        public bool? IsSports { get; set; }
        /// <summary>The Latitude property</summary>
        public double? Latitude { get; set; }
        /// <summary>Gets or sets the local trailer count.</summary>
        public int? LocalTrailerCount { get; set; }

		[JsonConverter(typeof(JsonStringEnumConverter<BaseItemDto_LocationType>))]
		/// <summary>Gets or sets the type of the location.</summary>
		public global::Jellyfin.Client.Models.BaseItemDto_LocationType? LocationType { get; set; }
        /// <summary>Gets or sets a value indicating whether [enable internet providers].</summary>
        public bool? LockData { get; set; }
        /// <summary>Gets or sets the locked fields.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.MetadataField?>? LockedFields { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.MetadataField?> LockedFields { get; set; }
#endif
        /// <summary>The Longitude property</summary>
        public double? Longitude { get; set; }
        /// <summary>The MediaSourceCount property</summary>
        public int? MediaSourceCount { get; set; }
        /// <summary>Gets or sets the media versions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.MediaSourceInfo>? MediaSources { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.MediaSourceInfo> MediaSources { get; set; }
#endif
        /// <summary>Gets or sets the media streams.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.MediaStream>? MediaStreams { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.MediaStream> MediaStreams { get; set; }
#endif

		[JsonConverter(typeof(JsonStringEnumConverter<BaseItemDto_MediaType>))]
		/// <summary>Media types.</summary>
		public global::Jellyfin.Client.Models.BaseItemDto_MediaType? MediaType { get; set; }
        /// <summary>Gets or sets the movie count.</summary>
        public int? MovieCount { get; set; }
        /// <summary>Gets or sets the music video count.</summary>
        public int? MusicVideoCount { get; set; }
        /// <summary>Gets or sets the name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Gets or sets the gain required for audio normalization.</summary>
        public float? NormalizationGain { get; set; }
        /// <summary>Gets or sets the number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Number { get; set; }
#nullable restore
#else
        public string Number { get; set; }
#endif
        /// <summary>Gets or sets the official rating.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OfficialRating { get; set; }
#nullable restore
#else
        public string OfficialRating { get; set; }
#endif
        /// <summary>The OriginalTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginalTitle { get; set; }
#nullable restore
#else
        public string OriginalTitle { get; set; }
#endif
        /// <summary>Gets or sets the overview.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Overview { get; set; }
#nullable restore
#else
        public string Overview { get; set; }
#endif
        /// <summary>Gets or sets the parent art image tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentArtImageTag { get; set; }
#nullable restore
#else
        public string ParentArtImageTag { get; set; }
#endif
        /// <summary>Gets or sets whether the item has fan art, this will hold the Id of the Parent that has one.</summary>
        public Guid? ParentArtItemId { get; set; }
        /// <summary>Gets or sets the parent backdrop image tags.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ParentBackdropImageTags { get; set; }
#nullable restore
#else
        public List<string> ParentBackdropImageTags { get; set; }
#endif
        /// <summary>Gets or sets whether the item has any backdrops, this will hold the Id of the Parent that has one.</summary>
        public Guid? ParentBackdropItemId { get; set; }
        /// <summary>Gets or sets the parent id.</summary>
        public Guid? ParentId { get; set; }
        /// <summary>Gets or sets the parent index number.</summary>
        public int? ParentIndexNumber { get; set; }
        /// <summary>Gets or sets the parent logo image tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentLogoImageTag { get; set; }
#nullable restore
#else
        public string ParentLogoImageTag { get; set; }
#endif
        /// <summary>Gets or sets whether the item has a logo, this will hold the Id of the Parent that has one.</summary>
        public Guid? ParentLogoItemId { get; set; }
        /// <summary>Gets or sets the parent primary image item identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentPrimaryImageItemId { get; set; }
#nullable restore
#else
        public string ParentPrimaryImageItemId { get; set; }
#endif
        /// <summary>Gets or sets the parent primary image tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentPrimaryImageTag { get; set; }
#nullable restore
#else
        public string ParentPrimaryImageTag { get; set; }
#endif
        /// <summary>Gets or sets the parent thumb image tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentThumbImageTag { get; set; }
#nullable restore
#else
        public string ParentThumbImageTag { get; set; }
#endif
        /// <summary>Gets or sets the parent thumb item id.</summary>
        public Guid? ParentThumbItemId { get; set; }
        /// <summary>Gets or sets the part count.</summary>
        public int? PartCount { get; set; }
        /// <summary>Gets or sets the path.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>Gets or sets the people.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.BaseItemPerson>? People { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.BaseItemPerson> People { get; set; }
#endif

		[JsonConverter(typeof(JsonStringEnumConverter<BaseItemDto_PlayAccess>))]
		/// <summary>Gets or sets the play access.</summary>
		public global::Jellyfin.Client.Models.BaseItemDto_PlayAccess? PlayAccess { get; set; }
        /// <summary>Gets or sets the playlist item identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlaylistItemId { get; set; }
#nullable restore
#else
        public string PlaylistItemId { get; set; }
#endif
        /// <summary>The PreferredMetadataCountryCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreferredMetadataCountryCode { get; set; }
#nullable restore
#else
        public string PreferredMetadataCountryCode { get; set; }
#endif
        /// <summary>The PreferredMetadataLanguage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreferredMetadataLanguage { get; set; }
#nullable restore
#else
        public string PreferredMetadataLanguage { get; set; }
#endif
        /// <summary>Gets or sets the premiere date.</summary>
        public DateTimeOffset? PremiereDate { get; set; }
        /// <summary>Gets or sets the primary image aspect ratio, after image enhancements.</summary>
        public double? PrimaryImageAspectRatio { get; set; }
        /// <summary>The ProductionLocations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ProductionLocations { get; set; }
#nullable restore
#else
        public List<string> ProductionLocations { get; set; }
#endif
        /// <summary>Gets or sets the production year.</summary>
        public int? ProductionYear { get; set; }
        /// <summary>The ProgramCount property</summary>
        public int? ProgramCount { get; set; }
        /// <summary>Gets or sets the program identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProgramId { get; set; }
#nullable restore
#else
        public string ProgramId { get; set; }
#endif
        /// <summary>Gets or sets the provider ids.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemDto_ProviderIds? ProviderIds { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemDto_ProviderIds ProviderIds { get; set; }
#endif
        /// <summary>Gets or sets the recursive item count.</summary>
        public int? RecursiveItemCount { get; set; }
        /// <summary>Gets or sets the trailer urls.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.MediaUrl>? RemoteTrailers { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.MediaUrl> RemoteTrailers { get; set; }
#endif
        /// <summary>Gets or sets the run time ticks.</summary>
        public long? RunTimeTicks { get; set; }
        /// <summary>Gets or sets the screenshot image tags.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ScreenshotImageTags { get; set; }
#nullable restore
#else
        public List<string> ScreenshotImageTags { get; set; }
#endif
        /// <summary>Gets or sets the season identifier.</summary>
        public Guid? SeasonId { get; set; }
        /// <summary>Gets or sets the name of the season.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SeasonName { get; set; }
#nullable restore
#else
        public string SeasonName { get; set; }
#endif
        /// <summary>Gets or sets the series count.</summary>
        public int? SeriesCount { get; set; }
        /// <summary>Gets or sets the series id.</summary>
        public Guid? SeriesId { get; set; }
        /// <summary>Gets or sets the name of the series.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SeriesName { get; set; }
#nullable restore
#else
        public string SeriesName { get; set; }
#endif
        /// <summary>Gets or sets the series primary image tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SeriesPrimaryImageTag { get; set; }
#nullable restore
#else
        public string SeriesPrimaryImageTag { get; set; }
#endif
        /// <summary>Gets or sets the series studio.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SeriesStudio { get; set; }
#nullable restore
#else
        public string SeriesStudio { get; set; }
#endif
        /// <summary>Gets or sets the series thumb image tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SeriesThumbImageTag { get; set; }
#nullable restore
#else
        public string SeriesThumbImageTag { get; set; }
#endif
        /// <summary>Gets or sets the series timer identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SeriesTimerId { get; set; }
#nullable restore
#else
        public string SeriesTimerId { get; set; }
#endif
        /// <summary>Gets or sets the server identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServerId { get; set; }
#nullable restore
#else
        public string ServerId { get; set; }
#endif
        /// <summary>The ShutterSpeed property</summary>
        public double? ShutterSpeed { get; set; }
        /// <summary>The Software property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Software { get; set; }
#nullable restore
#else
        public string Software { get; set; }
#endif
        /// <summary>Gets or sets the song count.</summary>
        public int? SongCount { get; set; }
        /// <summary>Gets or sets the name of the sort.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SortName { get; set; }
#nullable restore
#else
        public string SortName { get; set; }
#endif
        /// <summary>Gets or sets the type of the source.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceType { get; set; }
#nullable restore
#else
        public string SourceType { get; set; }
#endif
        /// <summary>Gets or sets the special feature count.</summary>
        public int? SpecialFeatureCount { get; set; }
        /// <summary>Gets or sets the start date of the recording, in UTC.</summary>
        public DateTimeOffset? StartDate { get; set; }
        /// <summary>Gets or sets the status.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>Gets or sets the studios.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.NameGuidPair>? Studios { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.NameGuidPair> Studios { get; set; }
#endif
        /// <summary>Gets or sets the taglines.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Taglines { get; set; }
#nullable restore
#else
        public List<string> Taglines { get; set; }
#endif
        /// <summary>Gets or sets the tags.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>Gets or sets the timer identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimerId { get; set; }
#nullable restore
#else
        public string TimerId { get; set; }
#endif
        /// <summary>Gets or sets the trailer count.</summary>
        public int? TrailerCount { get; set; }
        /// <summary>Gets or sets the trickplay manifest.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemDto_Trickplay? Trickplay { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemDto_Trickplay Trickplay { get; set; }
#endif

		[JsonConverter(typeof(JsonStringEnumConverter<BaseItemDto_Type>))]
		/// <summary>The base item kind.</summary>
		public global::Jellyfin.Client.Models.BaseItemDto_Type? Type { get; set; }
        /// <summary>Gets or sets the user data for this item based on the user it&apos;s being requested for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.UserItemDataDto? UserData { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.UserItemDataDto UserData { get; set; }
#endif

		[JsonConverter(typeof(JsonStringEnumConverter<BaseItemDto_Video3DFormat>))]
		/// <summary>Gets or sets the video3 D format.</summary>
		public global::Jellyfin.Client.Models.BaseItemDto_Video3DFormat? Video3DFormat { get; set; }

		[JsonConverter(typeof(JsonStringEnumConverter<BaseItemDto_VideoType>))]
		/// <summary>Gets or sets the type of the video.</summary>
		public global::Jellyfin.Client.Models.BaseItemDto_VideoType? VideoType { get; set; }
        /// <summary>The Width property</summary>
        public int? Width { get; set; }
    }
}
#pragma warning restore CS0618
