// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BaseItemDto_ImageOrientation
    #pragma warning restore CS1591
    {
        [JsonStringEnumMemberName("TopLeft")]

        TopLeft,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("TopRight")]

        TopRight,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("BottomRight")]

        BottomRight,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("BottomLeft")]

        BottomLeft,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("LeftTop")]

        LeftTop,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("RightTop")]

        RightTop,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("RightBottom")]

        RightBottom,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("LeftBottom")]

        LeftBottom,
        #pragma warning restore CS1591
    }
}
