// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the play access.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BaseItemDto_PlayAccess
    {
        [JsonStringEnumMemberName("Full")]

        Full,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("None")]

        None,
        #pragma warning restore CS1591
    }
}
