// <auto-generated/>
namespace Jellyfin.Client.Models
{
	/// <summary>Gets or sets the type of the channel.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BaseItemDto_ChannelType
    {
        [JsonStringEnumMemberName("TV")]

        TV,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Radio")]

        Radio,
        #pragma warning restore CS1591
    }
}
