// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the video3 D format.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BaseItemDto_Video3DFormat
    {
        [JsonStringEnumMemberName("HalfSideBySide")]

        HalfSideBySide,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("FullSideBySide")]

        FullSideBySide,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("FullTopAndBottom")]

        FullTopAndBottom,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("HalfTopAndBottom")]

        HalfTopAndBottom,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("MVC")]

        MVC,
        #pragma warning restore CS1591
    }
}
