// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the type of the location.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BaseItemDto_LocationType
    {
        [JsonStringEnumMemberName("FileSystem")]

        FileSystem,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Remote")]

        Remote,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Virtual")]

        Virtual,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Offline")]

        Offline,
        #pragma warning restore CS1591
    }
}
