// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>The base item kind.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BaseItemKind
    {
        [JsonStringEnumMemberName("AggregateFolder")]

        AggregateFolder,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Audio")]

        Audio,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("AudioBook")]

        AudioBook,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("BasePluginFolder")]

        BasePluginFolder,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Book")]

        Book,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("BoxSet")]

        BoxSet,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Channel")]

        Channel,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ChannelFolderItem")]

        ChannelFolderItem,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("CollectionFolder")]

        CollectionFolder,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Episode")]

        Episode,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Folder")]

        Folder,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Genre")]

        Genre,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ManualPlaylistsFolder")]

        ManualPlaylistsFolder,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Movie")]

        Movie,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("LiveTvChannel")]

        LiveTvChannel,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("LiveTvProgram")]

        LiveTvProgram,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("MusicAlbum")]

        MusicAlbum,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("MusicArtist")]

        MusicArtist,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("MusicGenre")]

        MusicGenre,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("MusicVideo")]

        MusicVideo,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Person")]

        Person,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Photo")]

        Photo,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("PhotoAlbum")]

        PhotoAlbum,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Playlist")]

        Playlist,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("PlaylistsFolder")]

        PlaylistsFolder,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Program")]

        Program,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Recording")]

        Recording,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Season")]

        Season,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Series")]

        Series,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Studio")]

        Studio,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Trailer")]

        Trailer,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("TvChannel")]

        TvChannel,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("TvProgram")]

        TvProgram,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("UserRootFolder")]

        UserRootFolder,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("UserView")]

        UserView,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Video")]

        Video,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Year")]

        Year,
        #pragma warning restore CS1591
    }
}
