// <auto-generated/>
namespace Jellyfin.Client.Models
{
	[global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BaseItemDto_ExtraType
    #pragma warning restore CS1591
    {
        [JsonStringEnumMemberName("Unknown")]

        Unknown,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Clip")]

        Clip,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Trailer")]

        Trailer,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("BehindTheScenes")]

        BehindTheScenes,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("DeletedScene")]

        DeletedScene,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Interview")]

        Interview,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Scene")]

        Scene,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Sample")]

        Sample,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ThemeSong")]

        ThemeSong,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ThemeVideo")]

        ThemeVideo,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Featurette")]

        Featurette,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Short")]

        Short,
        #pragma warning restore CS1591
    }
}
