// <auto-generated/>
#pragma warning disable CS0618
namespace Jellyfin.Client.Models
{
	/// <summary>
	/// Query result container.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BaseItemDtoQueryResult
    {
        /// <summary>Gets or sets the items.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.BaseItemDto>? Items { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.BaseItemDto> Items { get; set; }
#endif
    }
}
#pragma warning restore CS0618
