// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// The branding options.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BrandingOptions 
    {
        /// <summary>Gets or sets the custom CSS.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomCss { get; set; }
#nullable restore
#else
        public string CustomCss { get; set; }
#endif
        /// <summary>Gets or sets the login disclaimer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LoginDisclaimer { get; set; }
#nullable restore
#else
        public string LoginDisclaimer { get; set; }
#endif
        /// <summary>Gets or sets a value indicating whether to enable the splashscreen.</summary>
        public bool? SplashscreenEnabled { get; set; }
    }
}
#pragma warning restore CS0618
