// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class BufferRequestDto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BufferRequestDto 
    {
        /// <summary>Gets or sets a value indicating whether the client playback is unpaused.</summary>
        public bool? IsPlaying { get; set; }
        /// <summary>Gets or sets the playlist item identifier of the playing item.</summary>
        public Guid? PlaylistItemId { get; set; }
        /// <summary>Gets or sets the position ticks.</summary>
        public long? PositionTicks { get; set; }
        /// <summary>Gets or sets when the request has been made by the client.</summary>
        public DateTimeOffset? When { get; set; }
    }
}
#pragma warning restore CS0618
