// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Channel mapping options dto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChannelMappingOptionsDto 
    {
        /// <summary>Gets or sets list of mappings.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.NameValuePair>? Mappings { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.NameValuePair> Mappings { get; set; }
#endif
        /// <summary>Gets or sets list of provider channels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.NameIdPair>? ProviderChannels { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.NameIdPair> ProviderChannels { get; set; }
#endif
        /// <summary>Gets or sets provider name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProviderName { get; set; }
#nullable restore
#else
        public string ProviderName { get; set; }
#endif
        /// <summary>Gets or sets list of tuner channels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.TunerChannelMapping>? TunerChannels { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.TunerChannelMapping> TunerChannels { get; set; }
#endif
    }
}
#pragma warning restore CS0618
