// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ChannelFeatures 
    #pragma warning restore CS1591
    {
        /// <summary>Gets or sets the automatic refresh levels.</summary>
        public int? AutoRefreshLevels { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance can filter.</summary>
        public bool? CanFilter { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance can search.</summary>
        public bool? CanSearch { get; set; }
        /// <summary>Gets or sets the content types.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.ChannelMediaContentType?>? ContentTypes { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.ChannelMediaContentType?> ContentTypes { get; set; }
#endif
		/// <summary>Gets or sets the default sort orders.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
		public List<global::Jellyfin.Client.Models.ChannelItemSortField?>? DefaultSortFields { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.ChannelItemSortField?> DefaultSortFields { get; set; }
#endif
        /// <summary>Gets or sets the identifier.</summary>
        public Guid? Id { get; set; }
        /// <summary>Gets or sets the maximum number of records the channel allows retrieving at a time.</summary>
        public int? MaxPageSize { get; set; }
        /// <summary>Gets or sets the media types.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.ChannelMediaType?>? MediaTypes { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.ChannelMediaType?> MediaTypes { get; set; }
#endif
        /// <summary>Gets or sets the name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Gets or sets a value indicating whether [supports content downloading].</summary>
        public bool? SupportsContentDownloading { get; set; }
        /// <summary>Gets or sets a value indicating whether [supports latest media].</summary>
        public bool? SupportsLatestMedia { get; set; }
        /// <summary>Gets or sets a value indicating whether a sort ascending/descending toggle is supported.</summary>
        public bool? SupportsSortOrderToggle { get; set; }
    }
}
#pragma warning restore CS0618
