// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591

	[JsonConverter(typeof(JsonStringEnumConverter<ChannelMediaType>))]
    public enum ChannelMediaType
    #pragma warning restore CS1591
    {
        [JsonStringEnumMemberName("Audio")]

        Audio,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Video")]

        Video,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Photo")]

        Photo,
        #pragma warning restore CS1591
    }
}
