// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591

	[JsonConverter(typeof(JsonStringEnumConverter<ChannelMediaContentType>))]
    public enum ChannelMediaContentType
    #pragma warning restore CS1591
    {
        [JsonStringEnumMemberName("Clip")]

        Clip,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Podcast")]

        Podcast,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Trailer")]

        Trailer,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Movie")]

        Movie,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Episode")]

        Episode,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Song")]

        Song,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("MovieExtra")]

        MovieExtra,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("TvExtra")]

        TvExtra,
        #pragma warning restore CS1591
    }
}
