// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591

	[JsonConverter(typeof(JsonStringEnumConverter<ChannelItemSortField>))]
    public enum ChannelItemSortField
    #pragma warning restore CS1591
    {
        [JsonStringEnumMemberName("Name")]

        Name,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("CommunityRating")]

        CommunityRating,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("PremiereDate")]

        PremiereDate,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("DateCreated")]

        DateCreated,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Runtime")]

        Runtime,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("PlayCount")]

        PlayCount,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("CommunityPlayCount")]

        CommunityPlayCount,
        #pragma warning restore CS1591
    }
}
