// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class ChapterInfo.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChapterInfo 
    {
        /// <summary>The ImageDateModified property</summary>
        public DateTimeOffset? ImageDateModified { get; set; }
        /// <summary>Gets or sets the image path.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImagePath { get; set; }
#nullable restore
#else
        public string ImagePath { get; set; }
#endif
        /// <summary>The ImageTag property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImageTag { get; set; }
#nullable restore
#else
        public string ImageTag { get; set; }
#endif
        /// <summary>Gets or sets the name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Gets or sets the start position ticks.</summary>
        public long? StartPositionTicks { get; set; }

    }
}
#pragma warning restore CS0618
