// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Client capabilities dto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ClientCapabilitiesDto 
    {
        /// <summary>Gets or sets the app store url.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppStoreUrl { get; set; }
#nullable restore
#else
        public string AppStoreUrl { get; set; }
#endif
        /// <summary>Gets or sets the device profile.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.DeviceProfile? DeviceProfile { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.DeviceProfile DeviceProfile { get; set; }
#endif
        /// <summary>Gets or sets the icon url.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IconUrl { get; set; }
#nullable restore
#else
        public string IconUrl { get; set; }
#endif
        /// <summary>Gets or sets the list of playable media types.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.MediaType?>? PlayableMediaTypes { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.MediaType?> PlayableMediaTypes { get; set; }
#endif
        /// <summary>Gets or sets the list of supported commands.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.GeneralCommandType?>? SupportedCommands { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.GeneralCommandType?> SupportedCommands { get; set; }
#endif
        /// <summary>Gets or sets a value indicating whether session supports media control.</summary>
        public bool? SupportsMediaControl { get; set; }
        /// <summary>Gets or sets a value indicating whether session supports a persistent identifier.</summary>
        public bool? SupportsPersistentIdentifier { get; set; }
    }
}
#pragma warning restore CS0618
