// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the MediaBrowser.Model.Dlna.CodecType which this container must meet.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]

	[JsonConverter(typeof(JsonStringEnumConverter<CodecProfile_Type>))]
    public enum CodecProfile_Type
    {
        [JsonStringEnumMemberName("Video")]

        Video,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("VideoAudio")]

        VideoAudio,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Audio")]

        Audio,
        #pragma warning restore CS1591
    }
}
