// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CollectionCreationResult 
    #pragma warning restore CS1591
    {
        /// <summary>The Id property</summary>
        public Guid? Id { get; set; }
    }
}
#pragma warning restore CS0618
