// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Collection type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CollectionType
    {
        [JsonStringEnumMemberName("unknown")]

        Unknown,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("movies")]

        Movies,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("tvshows")]

        Tvshows,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("music")]

        Music,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("musicvideos")]

        Musicvideos,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("trailers")]

        Trailers,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("homevideos")]

        Homevideos,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("boxsets")]

        Boxsets,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("books")]

        Books,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("photos")]

        Photos,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("livetv")]

        Livetv,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("playlists")]

        Playlists,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("folders")]

        Folders,
        #pragma warning restore CS1591
    }
}
