// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ConfigImageTypes 
    #pragma warning restore CS1591
    {
        /// <summary>The BackdropSizes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? BackdropSizes { get; set; }
#nullable restore
#else
        public List<string> BackdropSizes { get; set; }
#endif
        /// <summary>The BaseUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BaseUrl { get; set; }
#nullable restore
#else
        public string BaseUrl { get; set; }
#endif
        /// <summary>The LogoSizes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? LogoSizes { get; set; }
#nullable restore
#else
        public List<string> LogoSizes { get; set; }
#endif
        /// <summary>The PosterSizes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PosterSizes { get; set; }
#nullable restore
#else
        public List<string> PosterSizes { get; set; }
#endif
        /// <summary>The ProfileSizes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ProfileSizes { get; set; }
#nullable restore
#else
        public List<string> ProfileSizes { get; set; }
#endif
        /// <summary>The SecureBaseUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SecureBaseUrl { get; set; }
#nullable restore
#else
        public string SecureBaseUrl { get; set; }
#endif
        /// <summary>The StillSizes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? StillSizes { get; set; }
#nullable restore
#else
        public List<string> StillSizes { get; set; }
#endif
    }
}
#pragma warning restore CS0618
