// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// The configuration page info.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConfigurationPageInfo 
    {
        /// <summary>Gets or sets the display name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>Gets or sets a value indicating whether the configurations page is enabled in the main menu.</summary>
        public bool? EnableInMainMenu { get; set; }
        /// <summary>Gets or sets the menu icon.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MenuIcon { get; set; }
#nullable restore
#else
        public string MenuIcon { get; set; }
#endif
        /// <summary>Gets or sets the menu section.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MenuSection { get; set; }
#nullable restore
#else
        public string MenuSection { get; set; }
#endif
        /// <summary>Gets or sets the name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Gets or sets the plugin id.</summary>
        public Guid? PluginId { get; set; }
    }
}
#pragma warning restore CS0618
