// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Create new playlist dto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreatePlaylistDto 
    {
        /// <summary>Gets or sets item ids to add to the playlist.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? Ids { get; set; }
#nullable restore
#else
        public List<Guid?> Ids { get; set; }
#endif
        /// <summary>Gets or sets a value indicating whether the playlist is public.</summary>
        public bool? IsPublic { get; set; }
        /// <summary>Gets or sets the media type.</summary>
        public global::Jellyfin.Client.Models.CreatePlaylistDto_MediaType? MediaType { get; set; }
        /// <summary>Gets or sets the name of the new playlist.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Gets or sets the user id.</summary>
        public Guid? UserId { get; set; }
        /// <summary>Gets or sets the playlist users.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.PlaylistUserPermissions>? Users { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.PlaylistUserPermissions> Users { get; set; }
#endif
    }
}
#pragma warning restore CS0618
