// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class CultureDto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CultureDto 
    {
        /// <summary>Gets the display name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>Gets the name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Gets the name of the three letter ISO language.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThreeLetterISOLanguageName { get; private set; }
#nullable restore
#else
        public string ThreeLetterISOLanguageName { get; private set; }
#endif
        /// <summary>The ThreeLetterISOLanguageNames property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ThreeLetterISOLanguageNames { get; set; }
#nullable restore
#else
        public List<string> ThreeLetterISOLanguageNames { get; set; }
#endif
        /// <summary>Gets the name of the two letter ISO language.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TwoLetterISOLanguageName { get; set; }
#nullable restore
#else
        public string TwoLetterISOLanguageName { get; set; }
#endif
    }
}
#pragma warning restore CS0618
