// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DayOfWeekObject
    #pragma warning restore CS1591
    {
        [JsonStringEnumMemberName("Sunday")]

        Sunday,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Monday")]

        Monday,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Tuesday")]

        Tuesday,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Wednesday")]

        Wednesday,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Thursday")]

        Thursday,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Friday")]

        Friday,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Saturday")]

        Saturday,
        #pragma warning restore CS1591
    }
}
