// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// A MediaBrowser.Model.Dlna.DeviceProfile represents a set of metadata which determines which content a certain device is able to play.&lt;br /&gt;Specifically, it defines the supported &lt;see cref=&quot;P:MediaBrowser.Model.Dlna.DeviceProfile.ContainerProfiles&quot;&gt;containers&lt;/see&gt; and&lt;see cref=&quot;P:MediaBrowser.Model.Dlna.DeviceProfile.CodecProfiles&quot;&gt;codecs&lt;/see&gt; (video and/or audio, including codec profiles and levels)the device is able to direct play (without transcoding or remuxing),as well as which &lt;see cref=&quot;P:MediaBrowser.Model.Dlna.DeviceProfile.TranscodingProfiles&quot;&gt;containers/codecs to transcode to&lt;/see&gt; in case it isn&apos;t.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeviceProfile 
    {
        /// <summary>Gets or sets the codec profiles.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.CodecProfile>? CodecProfiles { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.CodecProfile> CodecProfiles { get; set; }
#endif
        /// <summary>Gets or sets the container profiles. Failing to meet these optional conditions causes transcoding to occur.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.ContainerProfile>? ContainerProfiles { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.ContainerProfile> ContainerProfiles { get; set; }
#endif
        /// <summary>Gets or sets the direct play profiles.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.DirectPlayProfile>? DirectPlayProfiles { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.DirectPlayProfile> DirectPlayProfiles { get; set; }
#endif
        /// <summary>Gets or sets the unique internal identifier.</summary>
        public Guid? Id { get; set; }
        /// <summary>Gets or sets the maximum allowed bitrate for statically streamed content (= direct played files).</summary>
        public int? MaxStaticBitrate { get; set; }
        /// <summary>Gets or sets the maximum allowed bitrate for statically streamed (= direct played) music files.</summary>
        public int? MaxStaticMusicBitrate { get; set; }
        /// <summary>Gets or sets the maximum allowed bitrate for all streamed content.</summary>
        public int? MaxStreamingBitrate { get; set; }
        /// <summary>Gets or sets the maximum allowed bitrate for transcoded music streams.</summary>
        public int? MusicStreamingTranscodingBitrate { get; set; }
        /// <summary>Gets or sets the name of this device profile. User profiles must have a unique name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Gets or sets the subtitle profiles.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.SubtitleProfile>? SubtitleProfiles { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.SubtitleProfile> SubtitleProfiles { get; set; }
#endif
        /// <summary>Gets or sets the transcoding profiles.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.TranscodingProfile>? TranscodingProfiles { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.TranscodingProfile> TranscodingProfiles { get; set; }
#endif
    }
}
#pragma warning restore CS0618
