// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Query result container.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeviceInfoDtoQueryResult 
    {
        /// <summary>Gets or sets the items.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.DeviceInfoDto>? Items { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.DeviceInfoDto> Items { get; set; }
#endif
        /// <summary>Gets or sets the index of the first record in Items.</summary>
        public int? StartIndex { get; set; }
        /// <summary>Gets or sets the total number of records available.</summary>
        public int? TotalRecordCount { get; set; }
    }
}
#pragma warning restore CS0618
