// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the Dlna profile type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DirectPlayProfile_Type
    {
        [JsonStringEnumMemberName("Audio")]

        Audio,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Video")]

        Video,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Photo")]

        Photo,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Subtitle")]

        Subtitle,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Lyric")]

        Lyric,
        #pragma warning restore CS1591
    }
}
