// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Defines the display preferences for any item that supports them (usually Folders).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DisplayPreferencesDto 
    {
        /// <summary>Gets or sets the client.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Client { get; set; }
#nullable restore
#else
        public string Client { get; set; }
#endif
        /// <summary>Gets or sets the custom prefs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.DisplayPreferencesDto_CustomPrefs? CustomPrefs { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.DisplayPreferencesDto_CustomPrefs CustomPrefs { get; set; }
#endif
        /// <summary>Gets or sets the user id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Gets or sets the index by.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IndexBy { get; set; }
#nullable restore
#else
        public string IndexBy { get; set; }
#endif
        /// <summary>Gets or sets the height of the primary image.</summary>
        public int? PrimaryImageHeight { get; set; }
        /// <summary>Gets or sets the width of the primary image.</summary>
        public int? PrimaryImageWidth { get; set; }
        /// <summary>Gets or sets a value indicating whether [remember indexing].</summary>
        public bool? RememberIndexing { get; set; }
        /// <summary>Gets or sets a value indicating whether [remember sorting].</summary>
        public bool? RememberSorting { get; set; }
        /// <summary>An enum representing the axis that should be scrolled.</summary>
        public global::Jellyfin.Client.Models.DisplayPreferencesDto_ScrollDirection? ScrollDirection { get; set; }
        /// <summary>Gets or sets a value indicating whether to show backdrops on this item.</summary>
        public bool? ShowBackdrop { get; set; }
        /// <summary>Gets or sets a value indicating whether [show sidebar].</summary>
        public bool? ShowSidebar { get; set; }
        /// <summary>Gets or sets the sort by.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SortBy { get; set; }
#nullable restore
#else
        public string SortBy { get; set; }
#endif
        /// <summary>An enum representing the sorting order.</summary>
        public global::Jellyfin.Client.Models.DisplayPreferencesDto_SortOrder? SortOrder { get; set; }
        /// <summary>Gets or sets the type of the view.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ViewType { get; set; }
#nullable restore
#else
        public string ViewType { get; set; }
#endif
    }
}
#pragma warning restore CS0618
