// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>An enum representing the axis that should be scrolled.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DisplayPreferencesDto_ScrollDirection
    {
        [JsonStringEnumMemberName("Horizontal")]

        Horizontal,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Vertical")]

        Vertical,
        #pragma warning restore CS1591
    }
}
