// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>An enum representing the sorting order.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DisplayPreferencesDto_SortOrder
    {
        [JsonStringEnumMemberName("Ascending")]

        Ascending,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Descending")]

        Descending,
        #pragma warning restore CS1591
    }
}
