// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EndPointInfo 
    #pragma warning restore CS1591
    {
        /// <summary>The IsInNetwork property</summary>
        public bool? IsInNetwork { get; set; }
        /// <summary>The IsLocal property</summary>
        public bool? IsLocal { get; set; }
    }
}
#pragma warning restore CS0618
