// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the specific media type for this id. This is used to distinguish between the differentexternal id types for providers with multiple ids.A null value indicates there is no specific media type associated with the external id, or this is thedefault id for the external provider so there is no need to specify a type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ExternalIdInfo_Type
    {
        [JsonStringEnumMemberName("Album")]

        Album,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("AlbumArtist")]

        AlbumArtist,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Artist")]

        Artist,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("BoxSet")]

        BoxSet,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Episode")]

        Episode,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Movie")]

        Movie,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("OtherArtist")]

        OtherArtist,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Person")]

        Person,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ReleaseGroup")]

        ReleaseGroup,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Season")]

        Season,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Series")]

        Series,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Track")]

        Track,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Book")]

        Book,
        #pragma warning restore CS1591
    }
}
