// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets the type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FileSystemEntryInfo_Type
    {
        [JsonStringEnumMemberName("File")]

        File,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Directory")]

        Directory,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("NetworkComputer")]

        NetworkComputer,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("NetworkShare")]

        NetworkShare,
        #pragma warning restore CS1591
    }
}
