// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class FontFile.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FontFile 
    {
        /// <summary>Gets or sets the date created.</summary>
        public DateTimeOffset? DateCreated { get; set; }
        /// <summary>Gets or sets the date modified.</summary>
        public DateTimeOffset? DateModified { get; set; }
        /// <summary>Gets or sets the name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Gets or sets the size.</summary>
        public long? Size { get; set; }
    }
}
#pragma warning restore CS0618
