// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the action.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ForgotPasswordResult_Action
    {
        [JsonStringEnumMemberName("ContactAdmin")]

        ContactAdmin,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("PinCode")]

        PinCode,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("InNetworkRequired")]

        InNetworkRequired,
        #pragma warning restore CS1591
    }
}
