// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Forgot Password Pin enter request body DTO.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ForgotPasswordPinDto 
    {
        /// <summary>Gets or sets the entered pin to have the password reset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pin { get; set; }
#nullable restore
#else
        public string Pin { get; set; }
#endif
    }
}
#pragma warning restore CS0618
