// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>This exists simply to identify a set of known commands.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GeneralCommand_Name
    {
        [JsonStringEnumMemberName("MoveUp")]

        MoveUp,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("MoveDown")]

        MoveDown,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("MoveLeft")]

        MoveLeft,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("MoveRight")]

        MoveRight,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("PageUp")]

        PageUp,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("PageDown")]

        PageDown,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("PreviousLetter")]

        PreviousLetter,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("NextLetter")]

        NextLetter,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ToggleOsd")]

        ToggleOsd,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ToggleContextMenu")]

        ToggleContextMenu,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Select")]

        Select,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Back")]

        Back,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("TakeScreenshot")]

        TakeScreenshot,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SendKey")]

        SendKey,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SendString")]

        SendString,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("GoHome")]

        GoHome,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("GoToSettings")]

        GoToSettings,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("VolumeUp")]

        VolumeUp,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("VolumeDown")]

        VolumeDown,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Mute")]

        Mute,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Unmute")]

        Unmute,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ToggleMute")]

        ToggleMute,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SetVolume")]

        SetVolume,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SetAudioStreamIndex")]

        SetAudioStreamIndex,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SetSubtitleStreamIndex")]

        SetSubtitleStreamIndex,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ToggleFullscreen")]

        ToggleFullscreen,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("DisplayContent")]

        DisplayContent,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("GoToSearch")]

        GoToSearch,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("DisplayMessage")]

        DisplayMessage,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SetRepeatMode")]

        SetRepeatMode,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ChannelUp")]

        ChannelUp,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ChannelDown")]

        ChannelDown,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Guide")]

        Guide,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ToggleStats")]

        ToggleStats,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("PlayMediaSource")]

        PlayMediaSource,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("PlayTrailers")]

        PlayTrailers,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SetShuffleQueue")]

        SetShuffleQueue,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("PlayState")]

        PlayState,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("PlayNext")]

        PlayNext,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ToggleOsdMenu")]

        ToggleOsdMenu,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Play")]

        Play,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SetMaxStreamingBitrate")]

        SetMaxStreamingBitrate,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SetPlaybackOrder")]

        SetPlaybackOrder,
        #pragma warning restore CS1591
    }
}
