// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GeneralCommand 
    #pragma warning restore CS1591
    {
        /// <summary>The Arguments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.GeneralCommand_Arguments? Arguments { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.GeneralCommand_Arguments Arguments { get; set; }
#endif
        /// <summary>The ControllingUserId property</summary>
        public Guid? ControllingUserId { get; set; }
    }
}
#pragma warning restore CS0618
