// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Get programs dto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetProgramsDto 
    {
        /// <summary>Gets or sets the channels to return guide information for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? ChannelIds { get; set; }
#nullable restore
#else
        public List<Guid?> ChannelIds { get; set; }
#endif
        /// <summary>Gets or sets include image information in output.</summary>
        public bool? EnableImages { get; set; }
        /// <summary>Gets or sets the image types to include in the output.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.ImageType?>? EnableImageTypes { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.ImageType?> EnableImageTypes { get; set; }
#endif
        /// <summary>Gets or sets a value indicating whether retrieve total record count.</summary>
        public bool? EnableTotalRecordCount { get; set; }
        /// <summary>Gets or sets include user data.</summary>
        public bool? EnableUserData { get; set; }
        /// <summary>Gets or sets specify additional fields of information to return in the output.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.ItemFields?>? Fields { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.ItemFields?> Fields { get; set; }
#endif
        /// <summary>Gets or sets the genre ids to return guide information for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? GenreIds { get; set; }
#nullable restore
#else
        public List<Guid?> GenreIds { get; set; }
#endif
        /// <summary>Gets or sets the genres to return guide information for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Genres { get; set; }
#nullable restore
#else
        public List<string> Genres { get; set; }
#endif
        /// <summary>Gets or sets filter by programs that have completed airing, or not.</summary>
        public bool? HasAired { get; set; }
        /// <summary>Gets or sets the max number of images to return, per image type.</summary>
        public int? ImageTypeLimit { get; set; }
        /// <summary>Gets or sets filter by programs that are currently airing, or not.</summary>
        public bool? IsAiring { get; set; }
        /// <summary>Gets or sets filter for kids.</summary>
        public bool? IsKids { get; set; }
        /// <summary>Gets or sets filter for movies.</summary>
        public bool? IsMovie { get; set; }
        /// <summary>Gets or sets filter for news.</summary>
        public bool? IsNews { get; set; }
        /// <summary>Gets or sets filter for series.</summary>
        public bool? IsSeries { get; set; }
        /// <summary>Gets or sets filter for sports.</summary>
        public bool? IsSports { get; set; }
        /// <summary>Gets or sets filter by library series id.</summary>
        public Guid? LibrarySeriesId { get; set; }
        /// <summary>Gets or sets the maximum number of records to return.</summary>
        public int? Limit { get; set; }
        /// <summary>Gets or sets the maximum premiere end date.</summary>
        public DateTimeOffset? MaxEndDate { get; set; }
        /// <summary>Gets or sets the maximum premiere start date.</summary>
        public DateTimeOffset? MaxStartDate { get; set; }
        /// <summary>Gets or sets the minimum premiere end date.</summary>
        public DateTimeOffset? MinEndDate { get; set; }
        /// <summary>Gets or sets the minimum premiere start date.</summary>
        public DateTimeOffset? MinStartDate { get; set; }
        /// <summary>Gets or sets filter by series timer id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SeriesTimerId { get; set; }
#nullable restore
#else
        public string SeriesTimerId { get; set; }
#endif
        /// <summary>Gets or sets specify one or more sort orders, comma delimited. Options: Name, StartDate.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.ItemSortBy?>? SortBy { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.ItemSortBy?> SortBy { get; set; }
#endif
        /// <summary>Gets or sets sort order.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.SortOrder?>? SortOrder { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.SortOrder?> SortOrder { get; set; }
#endif
        /// <summary>Gets or sets the record index to start at. All items with a lower index will be dropped from the results.</summary>
        public int? StartIndex { get; set; }
        /// <summary>Gets or sets optional. Filter by user id.</summary>
        public Guid? UserId { get; set; }
       
    }
}
#pragma warning restore CS0618
