// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class GroupInfoDto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GroupInfoDto 
    {
        /// <summary>Gets the group identifier.</summary>
        public Guid? GroupId { get; set; }
        /// <summary>Gets the group name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupName { get; set; }
#nullable restore
#else
        public string GroupName { get; set; }
#endif
        /// <summary>Gets the date when this DTO has been created.</summary>
        public DateTimeOffset? LastUpdatedAt { get; set; }
        /// <summary>Gets the participants.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Participants { get; set; }
#nullable restore
#else
        public List<string> Participants { get; set; }
#endif
    }
}
#pragma warning restore CS0618
