// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets the group state.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GroupInfoDto_State
    {
        [JsonStringEnumMemberName("Idle")]

        Idle,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Waiting")]

        Waiting,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Paused")]

        Paused,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Playing")]

        Playing,
        #pragma warning restore CS1591
    }
}
