// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GuideInfo 
    #pragma warning restore CS1591
    {
        /// <summary>Gets or sets the end date.</summary>
        public DateTimeOffset? EndDate { get; set; }
        /// <summary>Gets or sets the start date.</summary>
        public DateTimeOffset? StartDate { get; set; }
    }
}
#pragma warning restore CS0618
