// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class IgnoreWaitRequestDto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IgnoreWaitRequestDto 
    {
        /// <summary>Gets or sets a value indicating whether the client should be ignored.</summary>
        public bool? IgnoreWait { get; set; }
    }
}
#pragma warning restore CS0618
