// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class ImageInfo.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ImageInfo 
    {
        /// <summary>Gets or sets the blurhash.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BlurHash { get; set; }
#nullable restore
#else
        public string BlurHash { get; set; }
#endif
        /// <summary>Gets or sets the height.</summary>
        public int? Height { get; set; }
        /// <summary>Gets or sets the index of the image.</summary>
        public int? ImageIndex { get; set; }
        /// <summary>Gets or sets the image tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImageTag { get; set; }
#nullable restore
#else
        public string ImageTag { get; set; }
#endif
        /// <summary>Gets or sets the type of the image.</summary>
        public global::Jellyfin.Client.Models.ImageInfo_ImageType? ImageType { get; set; }
        /// <summary>Gets or sets the path.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>Gets or sets the size.</summary>
        public long? Size { get; set; }
        /// <summary>Gets or sets the width.</summary>
        public int? Width { get; set; }
    }
}
#pragma warning restore CS0618
