// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ImageOption 
    #pragma warning restore CS1591
    {
        /// <summary>Gets or sets the limit.</summary>
        public int? Limit { get; set; }
        /// <summary>Gets or sets the minimum width.</summary>
        public int? MinWidth { get; set; }
        /// <summary>Gets or sets the type.</summary>
        public global::Jellyfin.Client.Models.ImageOption_Type? Type { get; set; }
    }
}
#pragma warning restore CS0618
