// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the type of the image.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ImageInfo_ImageType
    {
        [JsonStringEnumMemberName("Primary")]

        Primary,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Art")]

        Art,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Backdrop")]

        Backdrop,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Banner")]

        Banner,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Logo")]

        Logo,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Thumb")]

        Thumb,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Disc")]

        Disc,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Box")]

        Box,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Screenshot")]

        Screenshot,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Menu")]

        Menu,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Chapter")]

        Chapter,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("BoxRear")]

        BoxRear,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Profile")]

        Profile,
        #pragma warning restore CS1591
    }
}
