// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class LibrarySummary.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ItemCounts 
    {
        /// <summary>Gets or sets the album count.</summary>
        public int? AlbumCount { get; set; }
        /// <summary>Gets or sets the artist count.</summary>
        public int? ArtistCount { get; set; }
        /// <summary>Gets or sets the book count.</summary>
        public int? BookCount { get; set; }
        /// <summary>Gets or sets the box set count.</summary>
        public int? BoxSetCount { get; set; }
        /// <summary>Gets or sets the episode count.</summary>
        public int? EpisodeCount { get; set; }
        /// <summary>Gets or sets the item count.</summary>
        public int? ItemCount { get; set; }
        /// <summary>Gets or sets the movie count.</summary>
        public int? MovieCount { get; set; }
        /// <summary>Gets or sets the music video count.</summary>
        public int? MusicVideoCount { get; set; }
        /// <summary>Gets or sets the program count.</summary>
        public int? ProgramCount { get; set; }
        /// <summary>Gets or sets the series count.</summary>
        public int? SeriesCount { get; set; }
        /// <summary>Gets or sets the song count.</summary>
        public int? SongCount { get; set; }
        /// <summary>Gets or sets the trailer count.</summary>
        public int? TrailerCount { get; set; }
    }
}
#pragma warning restore CS0618
