// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>These represent sort orders.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ItemSortBy
    {
        [JsonStringEnumMemberName("Default")]

        Default,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("AiredEpisodeOrder")]

        AiredEpisodeOrder,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Album")]

        Album,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("AlbumArtist")]

        AlbumArtist,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Artist")]

        Artist,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("DateCreated")]

        DateCreated,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("OfficialRating")]

        OfficialRating,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("DatePlayed")]

        DatePlayed,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("PremiereDate")]

        PremiereDate,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("StartDate")]

        StartDate,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SortName")]

        SortName,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Name")]

        Name,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Random")]

        Random,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Runtime")]

        Runtime,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("CommunityRating")]

        CommunityRating,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ProductionYear")]

        ProductionYear,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("PlayCount")]

        PlayCount,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("CriticRating")]

        CriticRating,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("IsFolder")]

        IsFolder,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("IsUnplayed")]

        IsUnplayed,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("IsPlayed")]

        IsPlayed,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SeriesSortName")]

        SeriesSortName,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("VideoBitRate")]

        VideoBitRate,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("AirTime")]

        AirTime,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Studio")]

        Studio,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("IsFavoriteOrLiked")]

        IsFavoriteOrLiked,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("DateLastContentAdded")]

        DateLastContentAdded,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SeriesDatePlayed")]

        SeriesDatePlayed,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ParentIndexNumber")]

        ParentIndexNumber,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("IndexNumber")]

        IndexNumber,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SimilarityScore")]

        SimilarityScore,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SearchScore")]

        SearchScore,
        #pragma warning restore CS1591
    }
}
