// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Enum ItemFilter.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ItemFilter
    {
        [JsonStringEnumMemberName("IsFolder")]

        IsFolder,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("IsNotFolder")]

        IsNotFolder,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("IsUnplayed")]

        IsUnplayed,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("IsPlayed")]

        IsPlayed,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("IsFavorite")]

        IsFavorite,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("IsResumable")]

        IsResumable,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Likes")]

        Likes,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Dislikes")]

        Dislikes,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("IsFavoriteOrLikes")]

        IsFavoriteOrLikes,
        #pragma warning restore CS1591
    }
}
