// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Used to control the data that gets attached to DtoBaseItems.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ItemFields
    {
        [JsonStringEnumMemberName("AirTime")]

        AirTime,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("CanDelete")]

        CanDelete,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("CanDownload")]

        CanDownload,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ChannelInfo")]

        ChannelInfo,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Chapters")]

        Chapters,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Trickplay")]

        Trickplay,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ChildCount")]

        ChildCount,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("CumulativeRunTimeTicks")]

        CumulativeRunTimeTicks,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("CustomRating")]

        CustomRating,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("DateCreated")]

        DateCreated,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("DateLastMediaAdded")]

        DateLastMediaAdded,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("DisplayPreferencesId")]

        DisplayPreferencesId,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Etag")]

        Etag,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ExternalUrls")]

        ExternalUrls,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Genres")]

        Genres,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("HomePageUrl")]

        HomePageUrl,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ItemCounts")]

        ItemCounts,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("MediaSourceCount")]

        MediaSourceCount,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("MediaSources")]

        MediaSources,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("OriginalTitle")]

        OriginalTitle,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Overview")]

        Overview,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ParentId")]

        ParentId,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Path")]

        Path,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("People")]

        People,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("PlayAccess")]

        PlayAccess,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ProductionLocations")]

        ProductionLocations,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ProviderIds")]

        ProviderIds,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("PrimaryImageAspectRatio")]

        PrimaryImageAspectRatio,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("RecursiveItemCount")]

        RecursiveItemCount,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Settings")]

        Settings,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ScreenshotImageTags")]

        ScreenshotImageTags,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SeriesPrimaryImage")]

        SeriesPrimaryImage,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SeriesStudio")]

        SeriesStudio,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SortName")]

        SortName,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SpecialEpisodeNumbers")]

        SpecialEpisodeNumbers,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Studios")]

        Studios,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Taglines")]

        Taglines,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Tags")]

        Tags,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("RemoteTrailers")]

        RemoteTrailers,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("MediaStreams")]

        MediaStreams,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SeasonUserData")]

        SeasonUserData,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ServiceName")]

        ServiceName,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ThemeSongIds")]

        ThemeSongIds,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ThemeVideoIds")]

        ThemeVideoIds,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ExternalEtag")]

        ExternalEtag,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("PresentationUniqueKey")]

        PresentationUniqueKey,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("InheritedParentalRatingValue")]

        InheritedParentalRatingValue,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ExternalSeriesId")]

        ExternalSeriesId,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SeriesPresentationUniqueKey")]

        SeriesPresentationUniqueKey,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("DateLastRefreshed")]

        DateLastRefreshed,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("DateLastSaved")]

        DateLastSaved,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("RefreshState")]

        RefreshState,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ChannelImage")]

        ChannelImage,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("EnableMediaSourceDisplay")]

        EnableMediaSourceDisplay,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Width")]

        Width,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Height")]

        Height,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ExtraIds")]

        ExtraIds,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("LocalTrailerCount")]

        LocalTrailerCount,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("IsHD")]

        IsHD,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SpecialFeatureCount")]

        SpecialFeatureCount,
        #pragma warning restore CS1591
    }
}
