// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class JoinGroupRequestDto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class JoinGroupRequestDto 
    {
        /// <summary>Gets or sets the group identifier.</summary>
        public Guid? GroupId { get; set; }
    }
}
#pragma warning restore CS0618
