// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Library type options dto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LibraryTypeOptionsDto 
    {
        /// <summary>Gets or sets the default image options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.ImageOption>? DefaultImageOptions { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.ImageOption> DefaultImageOptions { get; set; }
#endif
        /// <summary>Gets or sets the image fetchers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.LibraryOptionInfoDto>? ImageFetchers { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.LibraryOptionInfoDto> ImageFetchers { get; set; }
#endif
        /// <summary>Gets or sets the metadata fetchers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.LibraryOptionInfoDto>? MetadataFetchers { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.LibraryOptionInfoDto> MetadataFetchers { get; set; }
#endif
        /// <summary>Gets or sets the supported image types.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.ImageType?>? SupportedImageTypes { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.ImageType?> SupportedImageTypes { get; set; }
#endif
        /// <summary>Gets or sets the type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
    }
}
#pragma warning restore CS0618
