// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Library options result dto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LibraryOptionsResultDto 
    {
        /// <summary>Gets or sets the list of lyric fetchers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.LibraryOptionInfoDto>? LyricFetchers { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.LibraryOptionInfoDto> LyricFetchers { get; set; }
#endif
        /// <summary>Gets or sets the metadata readers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.LibraryOptionInfoDto>? MetadataReaders { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.LibraryOptionInfoDto> MetadataReaders { get; set; }
#endif
        /// <summary>Gets or sets the metadata savers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.LibraryOptionInfoDto>? MetadataSavers { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.LibraryOptionInfoDto> MetadataSavers { get; set; }
#endif
        /// <summary>Gets or sets the subtitle fetchers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.LibraryOptionInfoDto>? SubtitleFetchers { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.LibraryOptionInfoDto> SubtitleFetchers { get; set; }
#endif
        /// <summary>Gets or sets the type options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.LibraryTypeOptionsDto>? TypeOptions { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.LibraryTypeOptionsDto> TypeOptions { get; set; }
#endif
    }
}
#pragma warning restore CS0618
