// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>An enum representing the options to disable embedded subs.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LibraryOptions_AllowEmbeddedSubtitles
    {
        [JsonStringEnumMemberName("AllowAll")]

        AllowAll,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("AllowText")]

        AllowText,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("AllowImage")]

        AllowImage,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("AllowNone")]

        AllowNone,
        #pragma warning restore CS1591
    }
}
