// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the status.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LiveTvServiceInfo_Status
    {
        [JsonStringEnumMemberName("Ok")]

        Ok,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Unavailable")]

        Unavailable,
        #pragma warning restore CS1591
    }
}
