// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LiveTvInfo 
    #pragma warning restore CS1591
    {
        /// <summary>Gets or sets the enabled users.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? EnabledUsers { get; set; }
#nullable restore
#else
        public List<string> EnabledUsers { get; set; }
#endif
        /// <summary>Gets or sets a value indicating whether this instance is enabled.</summary>
        public bool? IsEnabled { get; set; }
        /// <summary>Gets or sets the services.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.LiveTvServiceInfo>? Services { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.LiveTvServiceInfo> Services { get; set; }
#endif
    }
}
#pragma warning restore CS0618
