// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// LyricResponse model.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LyricDto 
    {
        /// <summary>Gets or sets a collection of individual lyric lines.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.LyricLine>? Lyrics { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.LyricLine> Lyrics { get; set; }
#endif
        /// <summary>Gets or sets Metadata for the lyrics.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.LyricMetadata? Metadata { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.LyricMetadata Metadata { get; set; }
#endif
    }
}
#pragma warning restore CS0618
