// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// LyricMetadata model.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LyricMetadata 
    {
        /// <summary>Gets or sets the album this song is on.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Album { get; set; }
#nullable restore
#else
        public string Album { get; set; }
#endif
        /// <summary>Gets or sets the song artist.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Artist { get; set; }
#nullable restore
#else
        public string Artist { get; set; }
#endif
        /// <summary>Gets or sets the author of the lyric data.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Author { get; set; }
#nullable restore
#else
        public string Author { get; set; }
#endif
        /// <summary>Gets or sets who the LRC file was created by.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? By { get; set; }
#nullable restore
#else
        public string By { get; set; }
#endif
        /// <summary>Gets or sets the software used to create the LRC file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Creator { get; set; }
#nullable restore
#else
        public string Creator { get; set; }
#endif
        /// <summary>Gets or sets a value indicating whether this lyric is synced.</summary>
        public bool? IsSynced { get; set; }
        /// <summary>Gets or sets the length of the song in ticks.</summary>
        public long? Length { get; set; }
        /// <summary>Gets or sets the lyric offset compared to audio in ticks.</summary>
        public long? Offset { get; set; }
        /// <summary>Gets or sets the title of the song.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>Gets or sets the version of the creator used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
    }
}
#pragma warning restore CS0618
