// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MediaSourceInfo_Video3DFormat
    #pragma warning restore CS1591
    {
        [JsonStringEnumMemberName("HalfSideBySide")]

        HalfSideBySide,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("FullSideBySide")]

        FullSideBySide,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("FullTopAndBottom")]

        FullTopAndBottom,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("HalfTopAndBottom")]

        HalfTopAndBottom,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("MVC")]

        MVC,
        #pragma warning restore CS1591
    }
}
