// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class MediaStream.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MediaStream 
    {
        /// <summary>Gets or sets the aspect ratio.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AspectRatio { get; set; }
#nullable restore
#else
        public string AspectRatio { get; set; }
#endif
        /// <summary>An enum representing formats of spatial audio.</summary>
        public global::Jellyfin.Client.Models.MediaStream_AudioSpatialFormat? AudioSpatialFormat { get; private set; }
        /// <summary>Gets or sets the average frame rate.</summary>
        public float? AverageFrameRate { get; set; }
        /// <summary>Gets or sets the bit depth.</summary>
        public int? BitDepth { get; set; }
        /// <summary>Gets or sets the bit rate.</summary>
        public int? BitRate { get; set; }
        /// <summary>Gets or sets the Dolby Vision bl present flag.</summary>
        public int? BlPresentFlag { get; set; }
        /// <summary>Gets or sets the channel layout.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChannelLayout { get; set; }
#nullable restore
#else
        public string ChannelLayout { get; set; }
#endif
        /// <summary>Gets or sets the channels.</summary>
        public int? Channels { get; set; }
        /// <summary>Gets or sets the codec.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Codec { get; set; }
#nullable restore
#else
        public string Codec { get; set; }
#endif
        /// <summary>Gets or sets the codec tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CodecTag { get; set; }
#nullable restore
#else
        public string CodecTag { get; set; }
#endif
        /// <summary>Gets or sets the codec time base.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CodecTimeBase { get; set; }
#nullable restore
#else
        public string CodecTimeBase { get; set; }
#endif
        /// <summary>Gets or sets the color primaries.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ColorPrimaries { get; set; }
#nullable restore
#else
        public string ColorPrimaries { get; set; }
#endif
        /// <summary>Gets or sets the color range.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ColorRange { get; set; }
#nullable restore
#else
        public string ColorRange { get; set; }
#endif
        /// <summary>Gets or sets the color space.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ColorSpace { get; set; }
#nullable restore
#else
        public string ColorSpace { get; set; }
#endif
        /// <summary>Gets or sets the color transfer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ColorTransfer { get; set; }
#nullable restore
#else
        public string ColorTransfer { get; set; }
#endif
        /// <summary>Gets or sets the comment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Comment { get; set; }
#nullable restore
#else
        public string Comment { get; set; }
#endif
        /// <summary>Gets or sets the method.</summary>
        public global::Jellyfin.Client.Models.MediaStream_DeliveryMethod? DeliveryMethod { get; set; }
        /// <summary>Gets or sets the delivery URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeliveryUrl { get; set; }
#nullable restore
#else
        public string DeliveryUrl { get; set; }
#endif
        /// <summary>The DisplayTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayTitle { get; private set; }
#nullable restore
#else
        public string DisplayTitle { get; private set; }
#endif
        /// <summary>Gets or sets the Dolby Vision bl signal compatibility id.</summary>
        public int? DvBlSignalCompatibilityId { get; set; }
        /// <summary>Gets or sets the Dolby Vision level.</summary>
        public int? DvLevel { get; set; }
        /// <summary>Gets or sets the Dolby Vision profile.</summary>
        public int? DvProfile { get; set; }
        /// <summary>Gets or sets the Dolby Vision version major.</summary>
        public int? DvVersionMajor { get; set; }
        /// <summary>Gets or sets the Dolby Vision version minor.</summary>
        public int? DvVersionMinor { get; set; }
        /// <summary>Gets or sets the Dolby Vision el present flag.</summary>
        public int? ElPresentFlag { get; set; }
        /// <summary>Gets or sets the height.</summary>
        public int? Height { get; set; }
        /// <summary>Gets or sets the index.</summary>
        public int? Index { get; set; }
        /// <summary>Gets or sets whether this instance is anamorphic.</summary>
        public bool? IsAnamorphic { get; set; }
        /// <summary>The IsAVC property</summary>
        public bool? IsAVC { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is default.</summary>
        public bool? IsDefault { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is external.</summary>
        public bool? IsExternal { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is external URL.</summary>
        public bool? IsExternalUrl { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is forced.</summary>
        public bool? IsForced { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is for the hearing impaired.</summary>
        public bool? IsHearingImpaired { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is interlaced.</summary>
        public bool? IsInterlaced { get; set; }
        /// <summary>The IsTextSubtitleStream property</summary>
        public bool? IsTextSubtitleStream { get; private set; }
        /// <summary>Gets or sets the language.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Language { get; set; }
#nullable restore
#else
        public string Language { get; set; }
#endif
        /// <summary>Gets or sets the level.</summary>
        public double? Level { get; set; }
        /// <summary>The LocalizedDefault property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocalizedDefault { get; set; }
#nullable restore
#else
        public string LocalizedDefault { get; set; }
#endif
        /// <summary>The LocalizedExternal property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocalizedExternal { get; set; }
#nullable restore
#else
        public string LocalizedExternal { get; set; }
#endif
        /// <summary>The LocalizedForced property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocalizedForced { get; set; }
#nullable restore
#else
        public string LocalizedForced { get; set; }
#endif
        /// <summary>The LocalizedHearingImpaired property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocalizedHearingImpaired { get; set; }
#nullable restore
#else
        public string LocalizedHearingImpaired { get; set; }
#endif
        /// <summary>The LocalizedUndefined property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocalizedUndefined { get; set; }
#nullable restore
#else
        public string LocalizedUndefined { get; set; }
#endif
        /// <summary>The NalLengthSize property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NalLengthSize { get; set; }
#nullable restore
#else
        public string NalLengthSize { get; set; }
#endif
        /// <summary>Gets or sets the length of the packet.</summary>
        public int? PacketLength { get; set; }
        /// <summary>Gets or sets the filename.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>Gets or sets the pixel format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PixelFormat { get; set; }
#nullable restore
#else
        public string PixelFormat { get; set; }
#endif
        /// <summary>Gets or sets the profile.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Profile { get; set; }
#nullable restore
#else
        public string Profile { get; set; }
#endif
        /// <summary>Gets or sets the real frame rate.</summary>
        public float? RealFrameRate { get; set; }
        /// <summary>Gets the framerate used as reference.Prefer AverageFrameRate, if that is null or an unrealistic valuethen fallback to RealFrameRate.</summary>
        public float? ReferenceFrameRate { get; private set; }
        /// <summary>Gets or sets the reference frames.</summary>
        public int? RefFrames { get; set; }
        /// <summary>Gets or sets the Rotation in degrees.</summary>
        public int? Rotation { get; set; }
        /// <summary>Gets or sets the Dolby Vision rpu present flag.</summary>
        public int? RpuPresentFlag { get; set; }
        /// <summary>Gets or sets the sample rate.</summary>
        public int? SampleRate { get; set; }
        /// <summary>Gets or sets the score.</summary>
        public int? Score { get; set; }
        /// <summary>Gets or sets a value indicating whether [supports external stream].</summary>
        public bool? SupportsExternalStream { get; set; }
        /// <summary>Gets or sets the time base.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeBase { get; set; }
#nullable restore
#else
        public string TimeBase { get; set; }
#endif
        /// <summary>Gets or sets the title.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>Gets or sets the type.</summary>
        public global::Jellyfin.Client.Models.MediaStream_Type? Type { get; set; }
        /// <summary>Gets the video dovi title.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VideoDoViTitle { get; private set; }
#nullable restore
#else
        public string VideoDoViTitle { get; private set; }
#endif
        /// <summary>An enum representing video ranges.</summary>
        public global::Jellyfin.Client.Models.MediaStream_VideoRange? VideoRange { get; private set; }
        /// <summary>An enum representing types of video ranges.</summary>
        public global::Jellyfin.Client.Models.MediaStream_VideoRangeType? VideoRangeType { get; private set; }
        /// <summary>Gets or sets the width.</summary>
        public int? Width { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Jellyfin.Client.Models.MediaStream"/> and sets the default values.
        /// </summary>
        public MediaStream()
        {
            AudioSpatialFormat = global::Jellyfin.Client.Models.MediaStream_AudioSpatialFormat.None;
        }
    }
}
#pragma warning restore CS0618
