// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>An enum representing video ranges.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MediaStream_VideoRange
    {
        [JsonStringEnumMemberName("Unknown")]

        Unknown,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SDR")]

        SDR,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("HDR")]

        HDR,
        #pragma warning restore CS1591
    }
}
