// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Defines the types of content an individual Jellyfin.Data.Entities.MediaSegment represents.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MediaSegmentDto_Type
    {
        [JsonStringEnumMemberName("Unknown")]

        Unknown,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Commercial")]

        Commercial,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Preview")]

        Preview,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Recap")]

        Recap,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Outro")]

        Outro,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Intro")]

        Intro,
        #pragma warning restore CS1591
    }
}
