// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MediaSourceInfo_Type
    #pragma warning restore CS1591
    {
        [JsonStringEnumMemberName("Default")]

        Default,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Grouping")]

        Grouping,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Placeholder")]

        Placeholder,
        #pragma warning restore CS1591
    }
}
