// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MediaSourceInfo_Timestamp
    #pragma warning restore CS1591
    {
        [JsonStringEnumMemberName("None")]

        None,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Zero")]

        Zero,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Valid")]

        Valid,
        #pragma warning restore CS1591
    }
}
