// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>An enum representing formats of spatial audio.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MediaStream_AudioSpatialFormat
    {
        [JsonStringEnumMemberName("None")]

        None,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("DolbyAtmos")]

        DolbyAtmos,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("DTSX")]

        DTSX,
        #pragma warning restore CS1591
    }
}
