// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Media Update Info Dto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MediaUpdateInfoDto 
    {
        /// <summary>Gets or sets the list of updates.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.MediaUpdateInfoPathDto>? Updates { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.MediaUpdateInfoPathDto> Updates { get; set; }
#endif
    }
}
#pragma warning restore CS0618
