// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MediaProtocol
    #pragma warning restore CS1591
    {
        [JsonStringEnumMemberName("File")]

        File,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Http")]

        Http,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Rtmp")]

        Rtmp,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Rtsp")]

        Rtsp,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Udp")]

        Udp,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Rtp")]

        Rtp,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Ftp")]

        Ftp,
        #pragma warning restore CS1591
    }
}
