// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>An enum representing types of video ranges.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MediaStream_VideoRangeType
    {
        [JsonStringEnumMemberName("Unknown")]

        Unknown,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SDR")]

        SDR,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("HDR10")]

        HDR10,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("HLG")]

        HLG,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("DOVI")]

        DOVI,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("DOVIWithHDR10")]

        DOVIWithHDR10,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("DOVIWithHLG")]

        DOVIWithHLG,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("DOVIWithSDR")]

        DOVIWithSDR,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("HDR10Plus")]

        HDR10Plus,
        #pragma warning restore CS1591
    }
}
