// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Api model for MediaSegment&apos;s.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MediaSegmentDto 
    {
        /// <summary>Gets or sets the end of the segment.</summary>
        public long? EndTicks { get; set; }
        /// <summary>Gets or sets the id of the media segment.</summary>
        public Guid? Id { get; set; }
        /// <summary>Gets or sets the id of the associated item.</summary>
        public Guid? ItemId { get; set; }
        /// <summary>Gets or sets the start of the segment.</summary>
        public long? StartTicks { get; set; }
        /// <summary>Defines the types of content an individual Jellyfin.Data.Entities.MediaSegment represents.</summary>
        public global::Jellyfin.Client.Models.MediaSegmentDto_Type? Type { get; set; }
    }
}
#pragma warning restore CS0618
