// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Media streaming protocol.Lowercase for backwards compatibility.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MediaSourceInfo_TranscodingSubProtocol
    {
        [JsonStringEnumMemberName("http")]

        Http,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("hls")]

        Hls,
        #pragma warning restore CS1591
    }
}
