// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class MetadataOptions.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MetadataOptions 
    {
        /// <summary>The DisabledImageFetchers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DisabledImageFetchers { get; set; }
#nullable restore
#else
        public List<string> DisabledImageFetchers { get; set; }
#endif
        /// <summary>The DisabledMetadataFetchers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DisabledMetadataFetchers { get; set; }
#nullable restore
#else
        public List<string> DisabledMetadataFetchers { get; set; }
#endif
        /// <summary>The DisabledMetadataSavers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DisabledMetadataSavers { get; set; }
#nullable restore
#else
        public List<string> DisabledMetadataSavers { get; set; }
#endif
        /// <summary>The ImageFetcherOrder property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ImageFetcherOrder { get; set; }
#nullable restore
#else
        public List<string> ImageFetcherOrder { get; set; }
#endif
        /// <summary>The ItemType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ItemType { get; set; }
#nullable restore
#else
        public string ItemType { get; set; }
#endif
        /// <summary>The LocalMetadataReaderOrder property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? LocalMetadataReaderOrder { get; set; }
#nullable restore
#else
        public List<string> LocalMetadataReaderOrder { get; set; }
#endif
        /// <summary>The MetadataFetcherOrder property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MetadataFetcherOrder { get; set; }
#nullable restore
#else
        public List<string> MetadataFetcherOrder { get; set; }
#endif
    }
}
#pragma warning restore CS0618
