// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Enum MetadataFields.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MetadataField
    {
        [JsonStringEnumMemberName("Cast")]

        Cast,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Genres")]

        Genres,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ProductionLocations")]

        ProductionLocations,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Studios")]

        Studios,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Tags")]

        Tags,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Name")]

        Name,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Overview")]

        Overview,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Runtime")]

        Runtime,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("OfficialRating")]

        OfficialRating,
        #pragma warning restore CS1591
    }
}
