// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MetadataEditorInfo 
    #pragma warning restore CS1591
    {
        /// <summary>The ContentType property</summary>
        public global::Jellyfin.Client.Models.MetadataEditorInfo_ContentType? ContentType { get; set; }
        /// <summary>The ContentTypeOptions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.NameValuePair>? ContentTypeOptions { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.NameValuePair> ContentTypeOptions { get; set; }
#endif
        /// <summary>The Countries property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.CountryInfo>? Countries { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.CountryInfo> Countries { get; set; }
#endif
        /// <summary>The Cultures property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.CultureDto>? Cultures { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.CultureDto> Cultures { get; set; }
#endif
        /// <summary>The ExternalIdInfos property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.ExternalIdInfo>? ExternalIdInfos { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.ExternalIdInfo> ExternalIdInfos { get; set; }
#endif
        /// <summary>The ParentalRatingOptions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.ParentalRating>? ParentalRatingOptions { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.ParentalRating> ParentalRatingOptions { get; set; }
#endif
    }
}
#pragma warning restore CS0618
