// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class MovePlaylistItemRequestDto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MovePlaylistItemRequestDto 
    {
        /// <summary>Gets or sets the new position.</summary>
        public int? NewIndex { get; set; }
        /// <summary>Gets or sets the playlist identifier of the item.</summary>
        public Guid? PlaylistItemId { get; set; }
    }
}
#pragma warning restore CS0618
