// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class NextItemRequestDto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NextItemRequestDto 
    {
        /// <summary>Gets or sets the playing item identifier.</summary>
        public Guid? PlaylistItemId { get; set; }
       
    }
}
#pragma warning restore CS0618
