// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Open live stream dto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OpenLiveStreamDto 
    {
        /// <summary>Gets or sets a value indicating whether always burn in subtitles when transcoding.</summary>
        public bool? AlwaysBurnInSubtitleWhenTranscoding { get; set; }
        /// <summary>Gets or sets the audio stream index.</summary>
        public int? AudioStreamIndex { get; set; }
        /// <summary>Gets or sets the device profile.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.DeviceProfile? DeviceProfile { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.DeviceProfile DeviceProfile { get; set; }
#endif
        /// <summary>Gets or sets the device play protocols.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.MediaProtocol?>? DirectPlayProtocols { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.MediaProtocol?> DirectPlayProtocols { get; set; }
#endif
        /// <summary>Gets or sets a value indicating whether to enable direct play.</summary>
        public bool? EnableDirectPlay { get; set; }
        /// <summary>Gets or sets a value indicating whether to enale direct stream.</summary>
        public bool? EnableDirectStream { get; set; }
        /// <summary>Gets or sets the item id.</summary>
        public Guid? ItemId { get; set; }
        /// <summary>Gets or sets the max audio channels.</summary>
        public int? MaxAudioChannels { get; set; }
        /// <summary>Gets or sets the max streaming bitrate.</summary>
        public int? MaxStreamingBitrate { get; set; }
        /// <summary>Gets or sets the open token.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OpenToken { get; set; }
#nullable restore
#else
        public string OpenToken { get; set; }
#endif
        /// <summary>Gets or sets the play session id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlaySessionId { get; set; }
#nullable restore
#else
        public string PlaySessionId { get; set; }
#endif
        /// <summary>Gets or sets the start time in ticks.</summary>
        public long? StartTimeTicks { get; set; }
        /// <summary>Gets or sets the subtitle stream index.</summary>
        public int? SubtitleStreamIndex { get; set; }
        /// <summary>Gets or sets the user id.</summary>
        public Guid? UserId { get; set; }
       
    }
}
#pragma warning restore CS0618
