// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class PingRequestDto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PingRequestDto 
    {
        /// <summary>Gets or sets the ping time.</summary>
        public long? Ping { get; set; }
       
    }
}
#pragma warning restore CS0618
