// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PinRedeemResult 
    #pragma warning restore CS1591
    {
        /// <summary>Gets or sets a value indicating whether this MediaBrowser.Model.Users.PinRedeemResult is success.</summary>
        public bool? Success { get; set; }
        /// <summary>Gets or sets the users reset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? UsersReset { get; set; }
#nullable restore
#else
        public List<string> UsersReset { get; set; }
#endif
       
    }
}
#pragma warning restore CS0618
