// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class PlayRequestDto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PlayRequestDto 
    {
        /// <summary>Gets or sets the position of the playing item in the queue.</summary>
        public int? PlayingItemPosition { get; set; }
        /// <summary>Gets or sets the playing queue.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? PlayingQueue { get; set; }
#nullable restore
#else
        public List<Guid?> PlayingQueue { get; set; }
#endif
        /// <summary>Gets or sets the start position ticks.</summary>
        public long? StartPositionTicks { get; set; }
     
    }
}
#pragma warning restore CS0618
