// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class PlaybackProgressInfo.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PlaybackProgressInfo 
    {
        /// <summary>The AspectRatio property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AspectRatio { get; set; }
#nullable restore
#else
        public string AspectRatio { get; set; }
#endif
        /// <summary>Gets or sets the index of the audio stream.</summary>
        public int? AudioStreamIndex { get; set; }
        /// <summary>The Brightness property</summary>
        public int? Brightness { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance can seek.</summary>
        public bool? CanSeek { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is muted.</summary>
        public bool? IsMuted { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is paused.</summary>
        public bool? IsPaused { get; set; }
        /// <summary>Gets or sets the item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemDto? Item { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemDto Item { get; set; }
#endif
        /// <summary>Gets or sets the item identifier.</summary>
        public Guid? ItemId { get; set; }
        /// <summary>Gets or sets the live stream identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LiveStreamId { get; set; }
#nullable restore
#else
        public string LiveStreamId { get; set; }
#endif
        /// <summary>Gets or sets the media version identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MediaSourceId { get; set; }
#nullable restore
#else
        public string MediaSourceId { get; set; }
#endif
        /// <summary>The NowPlayingQueue property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.QueueItem>? NowPlayingQueue { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.QueueItem> NowPlayingQueue { get; set; }
#endif
        /// <summary>Gets or sets the playback order.</summary>
        public global::Jellyfin.Client.Models.PlaybackProgressInfo_PlaybackOrder? PlaybackOrder { get; set; }
        /// <summary>The PlaybackStartTimeTicks property</summary>
        public long? PlaybackStartTimeTicks { get; set; }
        /// <summary>The PlaylistItemId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlaylistItemId { get; set; }
#nullable restore
#else
        public string PlaylistItemId { get; set; }
#endif
        /// <summary>Gets or sets the play method.</summary>
        public global::Jellyfin.Client.Models.PlaybackProgressInfo_PlayMethod? PlayMethod { get; set; }
        /// <summary>Gets or sets the play session identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlaySessionId { get; set; }
#nullable restore
#else
        public string PlaySessionId { get; set; }
#endif
        /// <summary>Gets or sets the position ticks.</summary>
        public long? PositionTicks { get; set; }
        /// <summary>Gets or sets the repeat mode.</summary>
        public global::Jellyfin.Client.Models.PlaybackProgressInfo_RepeatMode? RepeatMode { get; set; }
        /// <summary>Gets or sets the session id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SessionId { get; set; }
#nullable restore
#else
        public string SessionId { get; set; }
#endif
        /// <summary>Gets or sets the index of the subtitle stream.</summary>
        public int? SubtitleStreamIndex { get; set; }
        /// <summary>Gets or sets the volume level.</summary>
        public int? VolumeLevel { get; set; }
      
    }
}
#pragma warning restore CS0618
