// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the repeat mode.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PlaybackStartInfo_RepeatMode
    {
        [JsonStringEnumMemberName("RepeatNone")]

        RepeatNone,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("RepeatAll")]

        RepeatAll,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("RepeatOne")]

        RepeatOne,
        #pragma warning restore CS1591
    }
}
