// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// DTO for playlists.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PlaylistDto 
    {
        /// <summary>Gets or sets the item ids.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? ItemIds { get; set; }
#nullable restore
#else
        public List<Guid?> ItemIds { get; set; }
#endif
        /// <summary>Gets or sets a value indicating whether the playlist is publicly readable.</summary>
        public bool? OpenAccess { get; set; }
        /// <summary>Gets or sets the share permissions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.PlaylistUserPermissions>? Shares { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.PlaylistUserPermissions> Shares { get; set; }
#endif
    
    }
}
#pragma warning restore CS0618
