// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PlayerStateInfo 
    #pragma warning restore CS1591
    {
        /// <summary>Gets or sets the index of the now playing audio stream.</summary>
        public int? AudioStreamIndex { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance can seek.</summary>
        public bool? CanSeek { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is muted.</summary>
        public bool? IsMuted { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is paused.</summary>
        public bool? IsPaused { get; set; }
        /// <summary>Gets or sets the now playing live stream identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LiveStreamId { get; set; }
#nullable restore
#else
        public string LiveStreamId { get; set; }
#endif
        /// <summary>Gets or sets the now playing media version identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MediaSourceId { get; set; }
#nullable restore
#else
        public string MediaSourceId { get; set; }
#endif
		[JsonConverter(typeof(JsonStringEnumConverter<PlayerStateInfo_PlaybackOrder>))]
        /// <summary>Gets or sets the playback order.</summary>
        public global::Jellyfin.Client.Models.PlayerStateInfo_PlaybackOrder? PlaybackOrder { get; set; }

		[JsonConverter(typeof(JsonStringEnumConverter<PlayerStateInfo_PlayMethod>))]
		/// <summary>Gets or sets the play method.</summary>
		public global::Jellyfin.Client.Models.PlayerStateInfo_PlayMethod? PlayMethod { get; set; }
        /// <summary>Gets or sets the now playing position ticks.</summary>
        public long? PositionTicks { get; set; }

		[JsonConverter(typeof(JsonStringEnumConverter<PlayerStateInfo_RepeatMode>))]
		/// <summary>Gets or sets the repeat mode.</summary>
		public global::Jellyfin.Client.Models.PlayerStateInfo_RepeatMode? RepeatMode { get; set; }
        /// <summary>Gets or sets the index of the now playing subtitle stream.</summary>
        public int? SubtitleStreamIndex { get; set; }
        /// <summary>Gets or sets the volume level.</summary>
        public int? VolumeLevel { get; set; }
        
    }
}
#pragma warning restore CS0618
