// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class PlaybackStopInfo.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PlaybackStopInfo 
    {
        /// <summary>Gets or sets a value indicating whether this MediaBrowser.Model.Session.PlaybackStopInfo is failed.</summary>
        public bool? Failed { get; set; }
        /// <summary>Gets or sets the item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemDto? Item { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemDto Item { get; set; }
#endif
        /// <summary>Gets or sets the item identifier.</summary>
        public Guid? ItemId { get; set; }
        /// <summary>Gets or sets the live stream identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LiveStreamId { get; set; }
#nullable restore
#else
        public string LiveStreamId { get; set; }
#endif
        /// <summary>Gets or sets the media version identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MediaSourceId { get; set; }
#nullable restore
#else
        public string MediaSourceId { get; set; }
#endif
        /// <summary>The NextMediaType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextMediaType { get; set; }
#nullable restore
#else
        public string NextMediaType { get; set; }
#endif
        /// <summary>The NowPlayingQueue property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.QueueItem>? NowPlayingQueue { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.QueueItem> NowPlayingQueue { get; set; }
#endif
        /// <summary>The PlaylistItemId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlaylistItemId { get; set; }
#nullable restore
#else
        public string PlaylistItemId { get; set; }
#endif
        /// <summary>Gets or sets the play session identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlaySessionId { get; set; }
#nullable restore
#else
        public string PlaySessionId { get; set; }
#endif
        /// <summary>Gets or sets the position ticks.</summary>
        public long? PositionTicks { get; set; }
        /// <summary>Gets or sets the session id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SessionId { get; set; }
#nullable restore
#else
        public string SessionId { get; set; }
#endif
      
    }
}
#pragma warning restore CS0618
