// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the play method.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PlaybackProgressInfo_PlayMethod
    {
        [JsonStringEnumMemberName("Transcode")]

        Transcode,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("DirectStream")]

        DirectStream,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("DirectPlay")]

        DirectPlay,
        #pragma warning restore CS1591
    }
}
