// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the playback order.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PlaybackProgressInfo_PlaybackOrder
    {
        [JsonStringEnumMemberName("Default")]

        Default,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Shuffle")]

        Shuffle,
        #pragma warning restore CS1591
    }
}
