// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class to hold data on user permissions for playlists.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PlaylistUserPermissions 
    {
        /// <summary>Gets or sets a value indicating whether the user has edit permissions.</summary>
        public bool? CanEdit { get; set; }
        /// <summary>Gets or sets the user id.</summary>
        public Guid? UserId { get; set; }
      
    }
}
#pragma warning restore CS0618
