// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the error code.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PlaybackInfoResponse_ErrorCode
    {
        [JsonStringEnumMemberName("NotAllowed")]

        NotAllowed,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("NoCompatibleStream")]

        NoCompatibleStream,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("RateLimitExceeded")]

        RateLimitExceeded,
        #pragma warning restore CS1591
    }
}
