// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class PlaybackInfoResponse.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PlaybackInfoResponse 
    {
        /// <summary>Gets or sets the error code.</summary>
        public global::Jellyfin.Client.Models.PlaybackInfoResponse_ErrorCode? ErrorCode { get; set; }
        /// <summary>Gets or sets the media sources.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.MediaSourceInfo>? MediaSources { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.MediaSourceInfo> MediaSources { get; set; }
#endif
        /// <summary>Gets or sets the play session identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlaySessionId { get; set; }
#nullable restore
#else
        public string PlaySessionId { get; set; }
#endif
      
    }
}
#pragma warning restore CS0618
