// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// This is a serializable stub class that is used by the api to provide information about installed plugins.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PluginInfo 
    {
        /// <summary>Gets or sets a value indicating whether the plugin can be uninstalled.</summary>
        public bool? CanUninstall { get; set; }
        /// <summary>Gets or sets the name of the configuration file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConfigurationFileName { get; set; }
#nullable restore
#else
        public string ConfigurationFileName { get; set; }
#endif
        /// <summary>Gets or sets the description.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Gets or sets a value indicating whether this plugin has a valid image.</summary>
        public bool? HasImage { get; set; }
        /// <summary>Gets or sets the unique id.</summary>
        public Guid? Id { get; set; }
        /// <summary>Gets or sets the name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Gets or sets a value indicating the status of the plugin.</summary>
        public global::Jellyfin.Client.Models.PluginInfo_Status? Status { get; set; }
        /// <summary>Gets or sets the version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
   
    }
}
#pragma warning restore CS0618
