// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets a value indicating the status of the plugin.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PluginInfo_Status
    {
        [JsonStringEnumMemberName("Active")]

        Active,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Restart")]

        Restart,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Deleted")]

        Deleted,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Superceded")]

        Superceded,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Malfunctioned")]

        Malfunctioned,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("NotSupported")]

        NotSupported,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Disabled")]

        Disabled,
        #pragma warning restore CS1591
    }
}
