// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ProfileCondition_Property
    #pragma warning restore CS1591
    {
        [JsonStringEnumMemberName("AudioChannels")]

        AudioChannels,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("AudioBitrate")]

        AudioBitrate,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("AudioProfile")]

        AudioProfile,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Width")]

        Width,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Height")]

        Height,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Has64BitOffsets")]

        Has64BitOffsets,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("PacketLength")]

        PacketLength,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("VideoBitDepth")]

        VideoBitDepth,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("VideoBitrate")]

        VideoBitrate,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("VideoFramerate")]

        VideoFramerate,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("VideoLevel")]

        VideoLevel,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("VideoProfile")]

        VideoProfile,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("VideoTimestamp")]

        VideoTimestamp,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("IsAnamorphic")]

        IsAnamorphic,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("RefFrames")]

        RefFrames,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("NumAudioStreams")]

        NumAudioStreams,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("NumVideoStreams")]

        NumVideoStreams,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("IsSecondaryAudio")]

        IsSecondaryAudio,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("VideoCodecTag")]

        VideoCodecTag,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("IsAvc")]

        IsAvc,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("IsInterlaced")]

        IsInterlaced,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("AudioSampleRate")]

        AudioSampleRate,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("AudioBitDepth")]

        AudioBitDepth,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("VideoRangeType")]

        VideoRangeType,
        #pragma warning restore CS1591
    }
}
