// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProfileCondition 
    #pragma warning restore CS1591
    {
        /// <summary>The Condition property</summary>
        public global::Jellyfin.Client.Models.ProfileCondition_Condition? Condition { get; set; }
        /// <summary>The IsRequired property</summary>
        public bool? IsRequired { get; set; }
        /// <summary>The Property property</summary>
        public global::Jellyfin.Client.Models.ProfileCondition_Property? Property { get; set; }
        /// <summary>The Value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value { get; set; }
#nullable restore
#else
        public string Value { get; set; }
#endif
    }
}
#pragma warning restore CS0618
