// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ProfileCondition_Condition
    #pragma warning restore CS1591
    {
        [JsonStringEnumMemberName("Equals")]

        Equals,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("NotEquals")]

        NotEquals,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("LessThanEqual")]

        LessThanEqual,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("GreaterThanEqual")]

        GreaterThanEqual,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("EqualsAny")]

        EqualsAny,
        #pragma warning restore CS1591
    }
}
