// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class QueueItem 
    #pragma warning restore CS1591
    {
        /// <summary>The Id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The PlaylistItemId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlaylistItemId { get; set; }
#nullable restore
#else
        public string PlaylistItemId { get; set; }
#endif
    }
}
#pragma warning restore CS0618
