// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RecommendationDto 
    #pragma warning restore CS1591
    {
        /// <summary>The BaselineItemName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BaselineItemName { get; set; }
#nullable restore
#else
        public string BaselineItemName { get; set; }
#endif
        /// <summary>The CategoryId property</summary>
        public Guid? CategoryId { get; set; }
        /// <summary>The Items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.BaseItemDto>? Items { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.BaseItemDto> Items { get; set; }
#endif
      
    }
}
#pragma warning restore CS0618
