// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum RecommendationDto_RecommendationType
    #pragma warning restore CS1591
    {
        [JsonStringEnumMemberName("SimilarToRecentlyPlayed")]

        SimilarToRecentlyPlayed,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SimilarToLikedItem")]

        SimilarToLikedItem,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("HasDirectorFromRecentlyPlayed")]

        HasDirectorFromRecentlyPlayed,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("HasActorFromRecentlyPlayed")]

        HasActorFromRecentlyPlayed,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("HasLikedDirector")]

        HasLikedDirector,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("HasLikedActor")]

        HasLikedActor,
        #pragma warning restore CS1591
    }
}
