// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the type of the rating.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RemoteImageInfo_RatingType
    {
        [JsonStringEnumMemberName("Score")]

        Score,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Likes")]

        Likes,
        #pragma warning restore CS1591
    }
}
