// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class RemoteImageResult.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RemoteImageResult 
    {
        /// <summary>Gets or sets the images.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.RemoteImageInfo>? Images { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.RemoteImageInfo> Images { get; set; }
#endif
        /// <summary>Gets or sets the providers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Providers { get; set; }
#nullable restore
#else
        public List<string> Providers { get; set; }
#endif
       
    }
}
#pragma warning restore CS0618
