// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RemoteSearchResult 
    #pragma warning restore CS1591
    {
        /// <summary>The AlbumArtist property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.RemoteSearchResult? AlbumArtist { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.RemoteSearchResult AlbumArtist { get; set; }
#endif
        /// <summary>The Artists property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.RemoteSearchResult>? Artists { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.RemoteSearchResult> Artists { get; set; }
#endif
        /// <summary>The ImageUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImageUrl { get; set; }
#nullable restore
#else
        public string ImageUrl { get; set; }
#endif
        /// <summary>The IndexNumber property</summary>
        public int? IndexNumber { get; set; }
        /// <summary>The IndexNumberEnd property</summary>
        public int? IndexNumberEnd { get; set; }
        /// <summary>Gets or sets the name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The Overview property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Overview { get; set; }
#nullable restore
#else
        public string Overview { get; set; }
#endif
        /// <summary>The ParentIndexNumber property</summary>
        public int? ParentIndexNumber { get; set; }
        /// <summary>The PremiereDate property</summary>
        public DateTimeOffset? PremiereDate { get; set; }
        /// <summary>Gets or sets the year.</summary>
        public int? ProductionYear { get; set; }
        /// <summary>Gets or sets the provider ids.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.RemoteSearchResult_ProviderIds? ProviderIds { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.RemoteSearchResult_ProviderIds ProviderIds { get; set; }
#endif
        /// <summary>The SearchProviderName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SearchProviderName { get; set; }
#nullable restore
#else
        public string SearchProviderName { get; set; }
#endif
    }
}
#pragma warning restore CS0618
