// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class RemoveFromPlaylistRequestDto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RemoveFromPlaylistRequestDto 
    {
        /// <summary>Gets or sets a value indicating whether the playing item should be removed as well. Used only when clearing the playlist.</summary>
        public bool? ClearPlayingItem { get; set; }
        /// <summary>Gets or sets a value indicating whether the entire playlist should be cleared.</summary>
        public bool? ClearPlaylist { get; set; }
        /// <summary>Gets or sets the playlist identifiers of the items. Ignored when clearing the playlist.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? PlaylistItemIds { get; set; }
#nullable restore
#else
        public List<Guid?> PlaylistItemIds { get; set; }
#endif
    }
}
#pragma warning restore CS0618
