// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class RemoteImageInfo.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RemoteImageInfo 
    {
        /// <summary>Gets or sets the community rating.</summary>
        public double? CommunityRating { get; set; }
        /// <summary>Gets or sets the height.</summary>
        public int? Height { get; set; }
        /// <summary>Gets or sets the language.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Language { get; set; }
#nullable restore
#else
        public string Language { get; set; }
#endif
        /// <summary>Gets or sets the name of the provider.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProviderName { get; set; }
#nullable restore
#else
        public string ProviderName { get; set; }
#endif
        /// <summary>Gets or sets the type of the rating.</summary>
        public global::Jellyfin.Client.Models.RemoteImageInfo_RatingType? RatingType { get; set; }
        /// <summary>Gets or sets a url used for previewing a smaller version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThumbnailUrl { get; set; }
#nullable restore
#else
        public string ThumbnailUrl { get; set; }
#endif
        /// <summary>Gets or sets the type.</summary>
        public global::Jellyfin.Client.Models.RemoteImageInfo_Type? Type { get; set; }
        /// <summary>Gets or sets the URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>Gets or sets the vote count.</summary>
        public int? VoteCount { get; set; }
        /// <summary>Gets or sets the width.</summary>
        public int? Width { get; set; }
    
    }
}
#pragma warning restore CS0618
