// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class SearchHintResult.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SearchHintResult 
    {
        /// <summary>Gets the search hints.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.SearchHint>? SearchHints { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.SearchHint> SearchHints { get; set; }
#endif
    }
}
#pragma warning restore CS0618
