// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Media types.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SearchHint_MediaType
    {
        [JsonStringEnumMemberName("Unknown")]

        Unknown,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Video")]

        Video,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Audio")]

        Audio,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Photo")]

        Photo,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Book")]

        Book,
        #pragma warning restore CS1591
    }
}
