// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class SearchHintResult.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SearchHint 
    {
        /// <summary>Gets or sets the album.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Album { get; set; }
#nullable restore
#else
        public string Album { get; set; }
#endif
        /// <summary>Gets or sets the album artist.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlbumArtist { get; set; }
#nullable restore
#else
        public string AlbumArtist { get; set; }
#endif
        /// <summary>Gets or sets the album id.</summary>
        public Guid? AlbumId { get; set; }
        /// <summary>Gets or sets the artists.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Artists { get; set; }
#nullable restore
#else
        public List<string> Artists { get; set; }
#endif
        /// <summary>Gets or sets the backdrop image item identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BackdropImageItemId { get; set; }
#nullable restore
#else
        public string BackdropImageItemId { get; set; }
#endif
        /// <summary>Gets or sets the backdrop image tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BackdropImageTag { get; set; }
#nullable restore
#else
        public string BackdropImageTag { get; set; }
#endif
        /// <summary>Gets or sets the channel identifier.</summary>
        public Guid? ChannelId { get; set; }
        /// <summary>Gets or sets the name of the channel.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChannelName { get; set; }
#nullable restore
#else
        public string ChannelName { get; set; }
#endif
        /// <summary>Gets or sets the end date.</summary>
        public DateTimeOffset? EndDate { get; set; }
        /// <summary>Gets or sets the episode count.</summary>
        public int? EpisodeCount { get; set; }
        /// <summary>Gets or sets the item id.</summary>
        public Guid? Id { get; set; }
        /// <summary>Gets or sets the index number.</summary>
        public int? IndexNumber { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is folder.</summary>
        public bool? IsFolder { get; set; }
        /// <summary>Gets or sets the item id.</summary>
        [Obsolete("")]
        public Guid? ItemId { get; set; }
        /// <summary>Gets or sets the matched term.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MatchedTerm { get; set; }
#nullable restore
#else
        public string MatchedTerm { get; set; }
#endif
        /// <summary>Media types.</summary>
        public global::Jellyfin.Client.Models.SearchHint_MediaType? MediaType { get; set; }
        /// <summary>Gets or sets the name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Gets or sets the parent index number.</summary>
        public int? ParentIndexNumber { get; set; }
        /// <summary>Gets or sets the primary image aspect ratio.</summary>
        public double? PrimaryImageAspectRatio { get; set; }
        /// <summary>Gets or sets the image tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrimaryImageTag { get; set; }
#nullable restore
#else
        public string PrimaryImageTag { get; set; }
#endif
        /// <summary>Gets or sets the production year.</summary>
        public int? ProductionYear { get; set; }
        /// <summary>Gets or sets the run time ticks.</summary>
        public long? RunTimeTicks { get; set; }
        /// <summary>Gets or sets the series.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Series { get; set; }
#nullable restore
#else
        public string Series { get; set; }
#endif
        /// <summary>Gets or sets the song count.</summary>
        public int? SongCount { get; set; }
        /// <summary>Gets or sets the start date.</summary>
        public DateTimeOffset? StartDate { get; set; }
        /// <summary>Gets or sets the status.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>Gets or sets the thumb image item identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThumbImageItemId { get; set; }
#nullable restore
#else
        public string ThumbImageItemId { get; set; }
#endif
        /// <summary>Gets or sets the thumb image tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThumbImageTag { get; set; }
#nullable restore
#else
        public string ThumbImageTag { get; set; }
#endif
    }
}
#pragma warning restore CS0618
