// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class SeekRequestDto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SeekRequestDto 
    {
        /// <summary>Gets or sets the position ticks.</summary>
        public long? PositionTicks { get; set; }
        
    }
}
#pragma warning restore CS0618
