// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the day pattern.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SeriesTimerInfoDto_DayPattern
    {
        [JsonStringEnumMemberName("Daily")]

        Daily,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Weekdays")]

        Weekdays,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Weekends")]

        Weekends,
        #pragma warning restore CS1591
    }
}
