// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>The status of a series.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SeriesStatus
    {
        [JsonStringEnumMemberName("Continuing")]

        Continuing,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Ended")]

        Ended,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Unreleased")]

        Unreleased,
        #pragma warning restore CS1591
    }
}
