// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SeriesTimerInfoDto_KeepUntil
    #pragma warning restore CS1591
    {
        [JsonStringEnumMemberName("UntilDeleted")]

        UntilDeleted,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("UntilSpaceNeeded")]

        UntilSpaceNeeded,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("UntilWatched")]

        UntilWatched,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("UntilDate")]

        UntilDate,
        #pragma warning restore CS1591
    }
}
