// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the chapter image resolution.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ServerConfiguration_ChapterImageResolution
    {
        [JsonStringEnumMemberName("MatchSource")]

        MatchSource,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("P144")]

        P144,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("P240")]

        P240,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("P360")]

        P360,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("P480")]

        P480,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("P720")]

        P720,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("P1080")]

        P1080,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("P1440")]

        P1440,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("P2160")]

        P2160,
        #pragma warning restore CS1591
    }
}
