// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Represents the server configuration.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ServerConfiguration 
    {
        /// <summary>Gets or sets the number of days we should retain activity logs.</summary>
        public int? ActivityLogRetentionDays { get; set; }
        /// <summary>Gets or sets a value indicating whether clients should be allowed to upload logs.</summary>
        public bool? AllowClientLogUpload { get; set; }
        /// <summary>Gets or sets the cache path.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CachePath { get; set; }
#nullable restore
#else
        public string CachePath { get; set; }
#endif
        /// <summary>Gets or sets the list of cast receiver applications.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.CastReceiverApplication>? CastReceiverApplications { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.CastReceiverApplication> CastReceiverApplications { get; set; }
#endif
        /// <summary>Gets or sets the chapter image resolution.</summary>
        public global::Jellyfin.Client.Models.ServerConfiguration_ChapterImageResolution? ChapterImageResolution { get; set; }
        /// <summary>The CodecsUsed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CodecsUsed { get; set; }
#nullable restore
#else
        public List<string> CodecsUsed { get; set; }
#endif
        /// <summary>The ContentTypes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.NameValuePair>? ContentTypes { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.NameValuePair> ContentTypes { get; set; }
#endif
        /// <summary>Gets or sets the cors hosts.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CorsHosts { get; set; }
#nullable restore
#else
        public List<string> CorsHosts { get; set; }
#endif
        /// <summary>The DisableLiveTvChannelUserDataName property</summary>
        public bool? DisableLiveTvChannelUserDataName { get; set; }
        /// <summary>The DisplaySpecialsWithinSeasons property</summary>
        public bool? DisplaySpecialsWithinSeasons { get; set; }
        /// <summary>Gets or sets the dummy chapter duration in seconds, use 0 (zero) or less to disable generation alltogether.</summary>
        public int? DummyChapterDuration { get; set; }
        /// <summary>Gets or sets a value indicating whether [enable case sensitive item ids].</summary>
        public bool? EnableCaseSensitiveItemIds { get; set; }
        /// <summary>The EnableExternalContentInSuggestions property</summary>
        public bool? EnableExternalContentInSuggestions { get; set; }
        /// <summary>The EnableFolderView property</summary>
        public bool? EnableFolderView { get; set; }
        /// <summary>The EnableGroupingIntoCollections property</summary>
        public bool? EnableGroupingIntoCollections { get; set; }
        /// <summary>Gets or sets a value indicating whether to enable prometheus metrics exporting.</summary>
        public bool? EnableMetrics { get; set; }
        /// <summary>The EnableNormalizedItemByNameIds property</summary>
        public bool? EnableNormalizedItemByNameIds { get; set; }
        /// <summary>Gets or sets a value indicating whether slow server responses should be logged as a warning.</summary>
        public bool? EnableSlowResponseWarning { get; set; }
        /// <summary>The ImageExtractionTimeoutMs property</summary>
        public int? ImageExtractionTimeoutMs { get; set; }
        /// <summary>Gets or sets the image saving convention.</summary>
        public global::Jellyfin.Client.Models.ServerConfiguration_ImageSavingConvention? ImageSavingConvention { get; set; }
        /// <summary>Gets or sets the threshold in minutes after a inactive session gets closed automatically.If set to 0 the check for inactive sessions gets disabled.</summary>
        public int? InactiveSessionThreshold { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is port authorized.</summary>
        public bool? IsPortAuthorized { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is first run.</summary>
        public bool? IsStartupWizardCompleted { get; set; }
        /// <summary>Gets or sets the how many metadata refreshes can run concurrently.</summary>
        public int? LibraryMetadataRefreshConcurrency { get; set; }
        /// <summary>Gets or sets the delay in seconds that we will wait after a file system change to try and discover what has been added/removedSome delay is necessary with some items because their creation is not atomic.  It involves the creation of severaldifferent directories and files.</summary>
        public int? LibraryMonitorDelay { get; set; }
        /// <summary>Gets or sets the how the library scan fans out.</summary>
        public int? LibraryScanFanoutConcurrency { get; set; }
        /// <summary>Gets or sets the duration in seconds that we will wait after a library updated event before executing the library changed notification.</summary>
        public int? LibraryUpdateDuration { get; set; }
        /// <summary>Gets or sets the number of days we should retain log files.</summary>
        public int? LogFileRetentionDays { get; set; }
        /// <summary>Gets or sets the remaining minutes of a book that can be played while still saving playstate. If this percentage is crossed playstate will be reset to the beginning and the item will be marked watched.</summary>
        public int? MaxAudiobookResume { get; set; }
        /// <summary>Gets or sets the maximum percentage of an item that can be played while still saving playstate. If this percentage is crossed playstate will be reset to the beginning and the item will be marked watched.</summary>
        public int? MaxResumePct { get; set; }
        /// <summary>Gets or sets the metadata country code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MetadataCountryCode { get; set; }
#nullable restore
#else
        public string MetadataCountryCode { get; set; }
#endif
        /// <summary>The MetadataOptions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.MetadataOptions>? MetadataOptions { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.MetadataOptions> MetadataOptions { get; set; }
#endif
        /// <summary>Gets or sets the metadata path.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MetadataPath { get; set; }
#nullable restore
#else
        public string MetadataPath { get; set; }
#endif
        /// <summary>Gets or sets the minimum minutes of a book that must be played in order for playstate to be updated.</summary>
        public int? MinAudiobookResume { get; set; }
        /// <summary>Gets or sets the minimum duration that an item must have in order to be eligible for playstate updates..</summary>
        public int? MinResumeDurationSeconds { get; set; }
        /// <summary>Gets or sets the minimum percentage of an item that must be played in order for playstate to be updated.</summary>
        public int? MinResumePct { get; set; }
        /// <summary>Gets or sets the limit for parallel image encoding.</summary>
        public int? ParallelImageEncodingLimit { get; set; }
        /// <summary>The PathSubstitutions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.PathSubstitution>? PathSubstitutions { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.PathSubstitution> PathSubstitutions { get; set; }
#endif
        /// <summary>The PluginRepositories property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.RepositoryInfo>? PluginRepositories { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.RepositoryInfo> PluginRepositories { get; set; }
#endif
        /// <summary>Gets or sets the preferred metadata language.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreferredMetadataLanguage { get; set; }
#nullable restore
#else
        public string PreferredMetadataLanguage { get; set; }
#endif
        /// <summary>Gets or sets the last known version that was ran using the configuration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreviousVersion { get; set; }
#nullable restore
#else
        public string PreviousVersion { get; set; }
#endif
        /// <summary>Gets or sets the stringified PreviousVersion to be stored/loaded,because System.Version itself isn&apos;t xml-serializable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreviousVersionStr { get; set; }
#nullable restore
#else
        public string PreviousVersionStr { get; set; }
#endif
        /// <summary>Gets or sets a value indicating whether quick connect is available for use on this server.</summary>
        public bool? QuickConnectAvailable { get; set; }
        /// <summary>The RemoteClientBitrateLimit property</summary>
        public int? RemoteClientBitrateLimit { get; set; }
        /// <summary>Gets or sets a value indicating whether older plugins should automatically be deleted from the plugin folder.</summary>
        public bool? RemoveOldPlugins { get; set; }
        /// <summary>The SaveMetadataHidden property</summary>
        public bool? SaveMetadataHidden { get; set; }
        /// <summary>The ServerName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServerName { get; set; }
#nullable restore
#else
        public string ServerName { get; set; }
#endif
        /// <summary>The SkipDeserializationForBasicTypes property</summary>
        public bool? SkipDeserializationForBasicTypes { get; set; }
        /// <summary>Gets or sets the threshold for the slow response time warning in ms.</summary>
        public long? SlowResponseThresholdMs { get; set; }
        /// <summary>Gets or sets characters to be removed from strings to create a sort name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? SortRemoveCharacters { get; set; }
#nullable restore
#else
        public List<string> SortRemoveCharacters { get; set; }
#endif
        /// <summary>Gets or sets words to be removed from strings to create a sort name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? SortRemoveWords { get; set; }
#nullable restore
#else
        public List<string> SortRemoveWords { get; set; }
#endif
        /// <summary>Gets or sets characters to be replaced with a &apos; &apos; in strings to create a sort name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? SortReplaceCharacters { get; set; }
#nullable restore
#else
        public List<string> SortReplaceCharacters { get; set; }
#endif
        /// <summary>Gets or sets the trickplay options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.TrickplayOptions? TrickplayOptions { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.TrickplayOptions TrickplayOptions { get; set; }
#endif
        /// <summary>The UICulture property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UICulture { get; set; }
#nullable restore
#else
        public string UICulture { get; set; }
#endif
    }
}
#pragma warning restore CS0618
