// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the image saving convention.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ServerConfiguration_ImageSavingConvention
    {
        [JsonStringEnumMemberName("Legacy")]

        Legacy,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Compatible")]

        Compatible,
        #pragma warning restore CS1591
    }
}
