// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Session info DTO.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SessionInfoDto 
    {
        /// <summary>Gets or sets the additional users.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.SessionUserInfo>? AdditionalUsers { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.SessionUserInfo> AdditionalUsers { get; set; }
#endif
        /// <summary>Gets or sets the application version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApplicationVersion { get; set; }
#nullable restore
#else
        public string ApplicationVersion { get; set; }
#endif
        /// <summary>Gets or sets the client capabilities.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.ClientCapabilitiesDto? Capabilities { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.ClientCapabilitiesDto Capabilities { get; set; }
#endif
        /// <summary>Gets or sets the type of the client.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Client { get; set; }
#nullable restore
#else
        public string Client { get; set; }
#endif
        /// <summary>Gets or sets the device id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceId { get; set; }
#nullable restore
#else
        public string DeviceId { get; set; }
#endif
        /// <summary>Gets or sets the name of the device.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceName { get; set; }
#nullable restore
#else
        public string DeviceName { get; set; }
#endif
        /// <summary>Gets or sets the type of the device.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceType { get; set; }
#nullable restore
#else
        public string DeviceType { get; set; }
#endif
        /// <summary>Gets or sets a value indicating whether the session has a custom device name.</summary>
        public bool? HasCustomDeviceName { get; set; }
        /// <summary>Gets or sets the id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Gets or sets a value indicating whether this session is active.</summary>
        public bool? IsActive { get; set; }
        /// <summary>Gets or sets the last activity date.</summary>
        public DateTimeOffset? LastActivityDate { get; set; }
        /// <summary>Gets or sets the last paused date.</summary>
        public DateTimeOffset? LastPausedDate { get; set; }
        /// <summary>Gets or sets the last playback check in.</summary>
        public DateTimeOffset? LastPlaybackCheckIn { get; set; }
        /// <summary>Gets or sets the now playing item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemDto? NowPlayingItem { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemDto NowPlayingItem { get; set; }
#endif
        /// <summary>Gets or sets the now playing queue.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.QueueItem>? NowPlayingQueue { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.QueueItem> NowPlayingQueue { get; set; }
#endif
        /// <summary>Gets or sets the now playing queue full items.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.BaseItemDto>? NowPlayingQueueFullItems { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.BaseItemDto> NowPlayingQueueFullItems { get; set; }
#endif
        /// <summary>Gets or sets the now viewing item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemDto? NowViewingItem { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemDto NowViewingItem { get; set; }
#endif
        /// <summary>Gets or sets the playable media types.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.MediaType?>? PlayableMediaTypes { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.MediaType?> PlayableMediaTypes { get; set; }
#endif
        /// <summary>Gets or sets the playlist item id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlaylistItemId { get; set; }
#nullable restore
#else
        public string PlaylistItemId { get; set; }
#endif
        /// <summary>Gets or sets the play state.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.PlayerStateInfo? PlayState { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.PlayerStateInfo PlayState { get; set; }
#endif
        /// <summary>Gets or sets the remote end point.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RemoteEndPoint { get; set; }
#nullable restore
#else
        public string RemoteEndPoint { get; set; }
#endif
        /// <summary>Gets or sets the server id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServerId { get; set; }
#nullable restore
#else
        public string ServerId { get; set; }
#endif
        /// <summary>Gets or sets the supported commands.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.GeneralCommandType?>? SupportedCommands { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.GeneralCommandType?> SupportedCommands { get; set; }
#endif
        /// <summary>Gets or sets a value indicating whether the session supports media control.</summary>
        public bool? SupportsMediaControl { get; set; }
        /// <summary>Gets or sets a value indicating whether the session supports remote control.</summary>
        public bool? SupportsRemoteControl { get; set; }
        /// <summary>Gets or sets the transcoding info.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.TranscodingInfo? TranscodingInfo { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.TranscodingInfo TranscodingInfo { get; set; }
#endif
        /// <summary>Gets or sets the user id.</summary>
        public Guid? UserId { get; set; }
        /// <summary>Gets or sets the username.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserName { get; set; }
#nullable restore
#else
        public string UserName { get; set; }
#endif
        /// <summary>Gets or sets the user primary image tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserPrimaryImageTag { get; set; }
#nullable restore
#else
        public string UserPrimaryImageTag { get; set; }
#endif
    }
}
#pragma warning restore CS0618
