// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Set channel mapping dto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SetChannelMappingDto 
    {
        /// <summary>Gets or sets the provider channel id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProviderChannelId { get; set; }
#nullable restore
#else
        public string ProviderChannelId { get; set; }
#endif
        /// <summary>Gets or sets the provider id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProviderId { get; set; }
#nullable restore
#else
        public string ProviderId { get; set; }
#endif
        /// <summary>Gets or sets the tuner channel id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TunerChannelId { get; set; }
#nullable restore
#else
        public string TunerChannelId { get; set; }
#endif
    }
}
#pragma warning restore CS0618
