// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class SetPlaylistItemRequestDto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SetPlaylistItemRequestDto 
    {
        /// <summary>Gets or sets the playlist identifier of the playing item.</summary>
        public Guid? PlaylistItemId { get; set; }
        
    }
}
#pragma warning restore CS0618
