// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class SetRepeatModeRequestDto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SetRepeatModeRequestDto 
    {
        /// <summary>Gets or sets the repeat mode.</summary>
        public global::Jellyfin.Client.Models.SetRepeatModeRequestDto_Mode? Mode { get; set; }
        
    }
}
#pragma warning restore CS0618
