// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the shuffle mode.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SetShuffleModeRequestDto_Mode
    {
        [JsonStringEnumMemberName("Sorted")]

        Sorted,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Shuffle")]

        Shuffle,
        #pragma warning restore CS1591
    }
}
