// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class SetShuffleModeRequestDto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SetShuffleModeRequestDto 
    {
        /// <summary>Gets or sets the shuffle mode.</summary>
        public global::Jellyfin.Client.Models.SetShuffleModeRequestDto_Mode? Mode { get; set; }
       
    }
}
#pragma warning restore CS0618
