// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Startup remote access dto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StartupRemoteAccessDto 
    {
        /// <summary>Gets or sets a value indicating whether enable automatic port mapping.</summary>
        public bool? EnableAutomaticPortMapping { get; set; }
        /// <summary>Gets or sets a value indicating whether enable remote access.</summary>
        public bool? EnableRemoteAccess { get; set; }
        
    }
}
#pragma warning restore CS0618
