// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the delivery method.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SubtitleProfile_Method
    {
        [JsonStringEnumMemberName("Encode")]

        Encode,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Embed")]

        Embed,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("External")]

        External,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Hls")]

        Hls,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Drop")]

        Drop,
        #pragma warning restore CS1591
    }
}
