// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the state of the task.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TaskInfo_State
    {
        [JsonStringEnumMemberName("Idle")]

        Idle,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Cancelling")]

        Cancelling,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Running")]

        Running,
        #pragma warning restore CS1591
    }
}
