// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class TaskTriggerInfo.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TaskTriggerInfo 
    {
        /// <summary>Gets or sets the day of week.</summary>
        public global::Jellyfin.Client.Models.TaskTriggerInfo_DayOfWeek? DayOfWeek { get; set; }
        /// <summary>Gets or sets the interval.</summary>
        public long? IntervalTicks { get; set; }
        /// <summary>Gets or sets the maximum runtime ticks.</summary>
        public long? MaxRuntimeTicks { get; set; }
        /// <summary>Gets or sets the time of day.</summary>
        public long? TimeOfDayTicks { get; set; }
        /// <summary>Gets or sets the type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
    }
}
#pragma warning restore CS0618
