// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the status.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TaskResult_Status
    {
        [JsonStringEnumMemberName("Completed")]

        Completed,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Failed")]

        Failed,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Cancelled")]

        Cancelled,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Aborted")]

        Aborted,
        #pragma warning restore CS1591
    }
}
