// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TimerInfoDto 
    #pragma warning restore CS1591
    {
        /// <summary>Gets or sets the channel id of the recording.</summary>
        public Guid? ChannelId { get; set; }
        /// <summary>Gets or sets the channel name of the recording.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChannelName { get; set; }
#nullable restore
#else
        public string ChannelName { get; set; }
#endif
        /// <summary>The ChannelPrimaryImageTag property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChannelPrimaryImageTag { get; set; }
#nullable restore
#else
        public string ChannelPrimaryImageTag { get; set; }
#endif
        /// <summary>Gets or sets the end date of the recording, in UTC.</summary>
        public DateTimeOffset? EndDate { get; set; }
        /// <summary>Gets or sets the external channel identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalChannelId { get; set; }
#nullable restore
#else
        public string ExternalChannelId { get; set; }
#endif
        /// <summary>Gets or sets the external identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalId { get; set; }
#nullable restore
#else
        public string ExternalId { get; set; }
#endif
        /// <summary>Gets or sets the external program identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalProgramId { get; set; }
#nullable restore
#else
        public string ExternalProgramId { get; set; }
#endif
        /// <summary>Gets or sets the external series timer identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalSeriesTimerId { get; set; }
#nullable restore
#else
        public string ExternalSeriesTimerId { get; set; }
#endif
        /// <summary>Gets or sets the Id of the recording.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Gets or sets a value indicating whether this instance is post padding required.</summary>
        public bool? IsPostPaddingRequired { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is pre padding required.</summary>
        public bool? IsPrePaddingRequired { get; set; }
        /// <summary>The KeepUntil property</summary>
        public global::Jellyfin.Client.Models.TimerInfoDto_KeepUntil? KeepUntil { get; set; }
        /// <summary>Gets or sets the name of the recording.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Gets or sets the description of the recording.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Overview { get; set; }
#nullable restore
#else
        public string Overview { get; set; }
#endif
        /// <summary>Gets or sets the parent backdrop image tags.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ParentBackdropImageTags { get; set; }
#nullable restore
#else
        public List<string> ParentBackdropImageTags { get; set; }
#endif
        /// <summary>Gets or sets the Id of the Parent that has a backdrop if the item does not have one.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentBackdropItemId { get; set; }
#nullable restore
#else
        public string ParentBackdropItemId { get; set; }
#endif
        /// <summary>Gets or sets the post padding seconds.</summary>
        public int? PostPaddingSeconds { get; set; }
        /// <summary>Gets or sets the pre padding seconds.</summary>
        public int? PrePaddingSeconds { get; set; }
        /// <summary>Gets or sets the priority.</summary>
        public int? Priority { get; set; }
        /// <summary>Gets or sets the program identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProgramId { get; set; }
#nullable restore
#else
        public string ProgramId { get; set; }
#endif
        /// <summary>Gets or sets the program information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.BaseItemDto? ProgramInfo { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.BaseItemDto ProgramInfo { get; set; }
#endif
        /// <summary>Gets or sets the run time ticks.</summary>
        public long? RunTimeTicks { get; set; }
        /// <summary>Gets or sets the series timer identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SeriesTimerId { get; set; }
#nullable restore
#else
        public string SeriesTimerId { get; set; }
#endif
        /// <summary>Gets or sets the server identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServerId { get; set; }
#nullable restore
#else
        public string ServerId { get; set; }
#endif
        /// <summary>Gets or sets the name of the service.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServiceName { get; set; }
#nullable restore
#else
        public string ServiceName { get; set; }
#endif
        /// <summary>Gets or sets the start date of the recording, in UTC.</summary>
        public DateTimeOffset? StartDate { get; set; }
        /// <summary>Gets or sets the status.</summary>
        public global::Jellyfin.Client.Models.TimerInfoDto_Status? Status { get; set; }
        /// <summary>The Type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
    }
}
#pragma warning restore CS0618
