// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the status.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TimerInfoDto_Status
    {
        [JsonStringEnumMemberName("New")]

        New,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("InProgress")]

        InProgress,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Completed")]

        Completed,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Cancelled")]

        Cancelled,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ConflictedOk")]

        ConflictedOk,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ConflictedNotOk")]

        ConflictedNotOk,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Error")]

        Error,
        #pragma warning restore CS1591
    }
}
