// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class holding information on a runnning transcode.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TranscodingInfo 
    {
        /// <summary>Gets or sets the audio channels.</summary>
        public int? AudioChannels { get; set; }
        /// <summary>Gets or sets the thread count used for encoding.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AudioCodec { get; set; }
#nullable restore
#else
        public string AudioCodec { get; set; }
#endif
        /// <summary>Gets or sets the bitrate.</summary>
        public int? Bitrate { get; set; }
        /// <summary>Gets or sets the completion percentage.</summary>
        public double? CompletionPercentage { get; set; }
        /// <summary>Gets or sets the thread count used for encoding.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Container { get; set; }
#nullable restore
#else
        public string Container { get; set; }
#endif
        /// <summary>Gets or sets the framerate.</summary>
        public float? Framerate { get; set; }
        /// <summary>Gets or sets the hardware acceleration type.</summary>
        public global::Jellyfin.Client.Models.TranscodingInfo_HardwareAccelerationType? HardwareAccelerationType { get; set; }
        /// <summary>Gets or sets the video height.</summary>
        public int? Height { get; set; }
        /// <summary>Gets or sets a value indicating whether the audio is passed through.</summary>
        public bool? IsAudioDirect { get; set; }
        /// <summary>Gets or sets a value indicating whether the video is passed through.</summary>
        public bool? IsVideoDirect { get; set; }
        /// <summary>Gets or sets the transcode reasons.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.TranscodeReason?>? TranscodeReasons { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.TranscodeReason?> TranscodeReasons { get; set; }
#endif
        /// <summary>Gets or sets the thread count used for encoding.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VideoCodec { get; set; }
#nullable restore
#else
        public string VideoCodec { get; set; }
#endif
    }
}
#pragma warning restore CS0618
