// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the transcoding seek info mode.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TranscodingProfile_TranscodeSeekInfo
    {
        [JsonStringEnumMemberName("Auto")]

        Auto,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Bytes")]

        Bytes,
        #pragma warning restore CS1591
    }
}
