// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the encoding context.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TranscodingProfile_Context
    {
        [JsonStringEnumMemberName("Streaming")]

        Streaming,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Static")]

        Static,
        #pragma warning restore CS1591
    }
}
