// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the hardware acceleration type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TranscodingInfo_HardwareAccelerationType
    {
        [JsonStringEnumMemberName("none")]

        None,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("amf")]

        Amf,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("qsv")]

        Qsv,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("nvenc")]

        Nvenc,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("v4l2m2m")]

        V4l2m2m,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("vaapi")]

        Vaapi,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("videotoolbox")]

        Videotoolbox,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("rkmpp")]

        Rkmpp,
        #pragma warning restore CS1591
    }
}
