// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TranscodeReason
    #pragma warning restore CS1591
    {
        [JsonStringEnumMemberName("ContainerNotSupported")]

        ContainerNotSupported,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("VideoCodecNotSupported")]

        VideoCodecNotSupported,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("AudioCodecNotSupported")]

        AudioCodecNotSupported,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SubtitleCodecNotSupported")]

        SubtitleCodecNotSupported,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("AudioIsExternal")]

        AudioIsExternal,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("SecondaryAudioNotSupported")]

        SecondaryAudioNotSupported,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("VideoProfileNotSupported")]

        VideoProfileNotSupported,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("VideoLevelNotSupported")]

        VideoLevelNotSupported,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("VideoResolutionNotSupported")]

        VideoResolutionNotSupported,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("VideoBitDepthNotSupported")]

        VideoBitDepthNotSupported,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("VideoFramerateNotSupported")]

        VideoFramerateNotSupported,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("RefFramesNotSupported")]

        RefFramesNotSupported,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("AnamorphicVideoNotSupported")]

        AnamorphicVideoNotSupported,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("InterlacedVideoNotSupported")]

        InterlacedVideoNotSupported,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("AudioChannelsNotSupported")]

        AudioChannelsNotSupported,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("AudioProfileNotSupported")]

        AudioProfileNotSupported,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("AudioSampleRateNotSupported")]

        AudioSampleRateNotSupported,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("AudioBitDepthNotSupported")]

        AudioBitDepthNotSupported,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ContainerBitrateExceedsLimit")]

        ContainerBitrateExceedsLimit,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("VideoBitrateNotSupported")]

        VideoBitrateNotSupported,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("AudioBitrateNotSupported")]

        AudioBitrateNotSupported,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("UnknownVideoStreamInfo")]

        UnknownVideoStreamInfo,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("UnknownAudioStreamInfo")]

        UnknownAudioStreamInfo,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("DirectPlayError")]

        DirectPlayError,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("VideoRangeTypeNotSupported")]

        VideoRangeTypeNotSupported,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("VideoCodecTagNotSupported")]

        VideoCodecTagNotSupported,
        #pragma warning restore CS1591
    }
}
