// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class TrickplayOptions.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TrickplayOptions 
    {
        /// <summary>Gets or sets a value indicating whether or not to use HW acceleration.</summary>
        public bool? EnableHwAcceleration { get; set; }
        /// <summary>Gets or sets a value indicating whether or not to use HW accelerated MJPEG encoding.</summary>
        public bool? EnableHwEncoding { get; set; }
        /// <summary>Gets or sets a value indicating whether to only extract key frames.Significantly faster, but is not compatible with all decoders and/or video files.</summary>
        public bool? EnableKeyFrameOnlyExtraction { get; set; }
        /// <summary>Gets or sets the interval, in ms, between each new trickplay image.</summary>
        public int? Interval { get; set; }
        /// <summary>Gets or sets the jpeg quality to use for image tiles.</summary>
        public int? JpegQuality { get; set; }
        /// <summary>Gets or sets the process priority for the ffmpeg process.</summary>
        public global::Jellyfin.Client.Models.TrickplayOptions_ProcessPriority? ProcessPriority { get; set; }
        /// <summary>Gets or sets the number of threads to be used by ffmpeg.</summary>
        public int? ProcessThreads { get; set; }
        /// <summary>Gets or sets the ffmpeg output quality level.</summary>
        public int? Qscale { get; set; }
        /// <summary>Gets or sets the behavior used by trickplay provider on library scan/update.</summary>
        public global::Jellyfin.Client.Models.TrickplayOptions_ScanBehavior? ScanBehavior { get; set; }
        /// <summary>Gets or sets number of tile images to allow in Y dimension.</summary>
        public int? TileHeight { get; set; }
        /// <summary>Gets or sets number of tile images to allow in X dimension.</summary>
        public int? TileWidth { get; set; }
        /// <summary>Gets or sets the target width resolutions, in px, to generates preview images for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? WidthResolutions { get; set; }
#nullable restore
#else
        public List<int?> WidthResolutions { get; set; }
#endif
    }
}
#pragma warning restore CS0618
