// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the process priority for the ffmpeg process.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TrickplayOptions_ProcessPriority
    {
        [JsonStringEnumMemberName("Normal")]

        Normal,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Idle")]

        Idle,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("High")]

        High,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("RealTime")]

        RealTime,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("BelowNormal")]

        BelowNormal,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("AboveNormal")]

        AboveNormal,
        #pragma warning restore CS1591
    }
}
