// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the behavior used by trickplay provider on library scan/update.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TrickplayOptions_ScanBehavior
    {
        [JsonStringEnumMemberName("Blocking")]

        Blocking,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("NonBlocking")]

        NonBlocking,
        #pragma warning restore CS1591
    }
}
