// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TypeOptions 
    #pragma warning restore CS1591
    {
        /// <summary>The ImageFetcherOrder property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ImageFetcherOrder { get; set; }
#nullable restore
#else
        public List<string> ImageFetcherOrder { get; set; }
#endif
        /// <summary>The ImageFetchers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ImageFetchers { get; set; }
#nullable restore
#else
        public List<string> ImageFetchers { get; set; }
#endif
        /// <summary>The ImageOptions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.ImageOption>? ImageOptions { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.ImageOption> ImageOptions { get; set; }
#endif
        /// <summary>The MetadataFetcherOrder property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MetadataFetcherOrder { get; set; }
#nullable restore
#else
        public List<string> MetadataFetcherOrder { get; set; }
#endif
        /// <summary>The MetadataFetchers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MetadataFetchers { get; set; }
#nullable restore
#else
        public List<string> MetadataFetchers { get; set; }
#endif
        /// <summary>The Type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
    }
}
#pragma warning restore CS0618
