// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>An enum representing an unrated item.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UnratedItem
    {
        [JsonStringEnumMemberName("Movie")]

        Movie,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Trailer")]

        Trailer,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Series")]

        Series,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Music")]

        Music,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Book")]

        Book,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("LiveTvChannel")]

        LiveTvChannel,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("LiveTvProgram")]

        LiveTvProgram,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("ChannelContent")]

        ChannelContent,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Other")]

        Other,
        #pragma warning restore CS1591
    }
}
