// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Update existing playlist dto. Fields set to `null` will not be updated and keep their current values.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdatePlaylistDto 
    {
        /// <summary>Gets or sets item ids of the playlist.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? Ids { get; set; }
#nullable restore
#else
        public List<Guid?> Ids { get; set; }
#endif
        /// <summary>Gets or sets a value indicating whether the playlist is public.</summary>
        public bool? IsPublic { get; set; }
        /// <summary>Gets or sets the name of the new playlist.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Gets or sets the playlist users.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.PlaylistUserPermissions>? Users { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.PlaylistUserPermissions> Users { get; set; }
#endif
    }
}
#pragma warning restore CS0618
