// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// The update user password request body.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateUserPassword 
    {
        /// <summary>Gets or sets the current sha1-hashed password.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrentPassword { get; set; }
#nullable restore
#else
        public string CurrentPassword { get; set; }
#endif
        /// <summary>Gets or sets the current plain text password.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrentPw { get; set; }
#nullable restore
#else
        public string CurrentPw { get; set; }
#endif
        /// <summary>Gets or sets the new plain text password.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NewPw { get; set; }
#nullable restore
#else
        public string NewPw { get; set; }
#endif
        /// <summary>Gets or sets a value indicating whether to reset the password.</summary>
        public bool? ResetPassword { get; set; }
        
    }
}
#pragma warning restore CS0618
