// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Update library options dto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateLibraryOptionsDto 
    {
        /// <summary>Gets or sets the library item id.</summary>
        public Guid? Id { get; set; }
        /// <summary>Gets or sets library options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.LibraryOptions? LibraryOptions { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.LibraryOptions LibraryOptions { get; set; }
#endif
    }
}
#pragma warning restore CS0618
