// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Update existing playlist user dto. Fields set to `null` will not be updated and keep their current values.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdatePlaylistUserDto 
    {
        /// <summary>Gets or sets a value indicating whether the user can edit the playlist.</summary>
        public bool? CanEdit { get; set; }
    }
}
#pragma warning restore CS0618
