// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Enum SyncPlayUserAccessType.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UserPolicy_SyncPlayAccess
    {
        [JsonStringEnumMemberName("CreateAndJoinGroups")]

        CreateAndJoinGroups,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("JoinGroups")]

        JoinGroups,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("None")]

        None,
        #pragma warning restore CS1591
    }
}
