// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class UserItemDataDto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserItemDataDto 
    {
        /// <summary>Gets or sets a value indicating whether this instance is favorite.</summary>
        public bool? IsFavorite { get; set; }
        /// <summary>Gets or sets the item identifier.</summary>
        public Guid? ItemId { get; set; }
        /// <summary>Gets or sets the key.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>Gets or sets the last played date.</summary>
        public DateTimeOffset? LastPlayedDate { get; set; }
        /// <summary>Gets or sets a value indicating whether this MediaBrowser.Model.Dto.UserItemDataDto is likes.</summary>
        public bool? Likes { get; set; }
        /// <summary>Gets or sets the playback position ticks.</summary>
        public long? PlaybackPositionTicks { get; set; }
        /// <summary>Gets or sets the play count.</summary>
        public int? PlayCount { get; set; }
        /// <summary>Gets or sets a value indicating whether this MediaBrowser.Model.Dto.UserItemDataDto is played.</summary>
        public bool? Played { get; set; }
        /// <summary>Gets or sets the played percentage.</summary>
        public double PlayedPercentage { get; set; }
        /// <summary>Gets or sets the rating.</summary>
        public double? Rating { get; set; }
        /// <summary>Gets or sets the unplayed item count.</summary>
        public int UnplayedItemCount { get; set; }

    }
}
#pragma warning restore CS0618
