// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UserPolicy 
    #pragma warning restore CS1591
    {
        /// <summary>The AccessSchedules property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.AccessSchedule>? AccessSchedules { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.AccessSchedule> AccessSchedules { get; set; }
#endif
        /// <summary>The AllowedTags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AllowedTags { get; set; }
#nullable restore
#else
        public List<string> AllowedTags { get; set; }
#endif
        /// <summary>The AuthenticationProviderId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthenticationProviderId { get; set; }
#nullable restore
#else
        public string AuthenticationProviderId { get; set; }
#endif
        /// <summary>The BlockedChannels property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? BlockedChannels { get; set; }
#nullable restore
#else
        public List<Guid?> BlockedChannels { get; set; }
#endif
        /// <summary>The BlockedMediaFolders property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? BlockedMediaFolders { get; set; }
#nullable restore
#else
        public List<Guid?> BlockedMediaFolders { get; set; }
#endif
        /// <summary>The BlockedTags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? BlockedTags { get; set; }
#nullable restore
#else
        public List<string> BlockedTags { get; set; }
#endif
        /// <summary>The BlockUnratedItems property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Jellyfin.Client.Models.UnratedItem?>? BlockUnratedItems { get; set; }
#nullable restore
#else
        public List<global::Jellyfin.Client.Models.UnratedItem?> BlockUnratedItems { get; set; }
#endif
        /// <summary>The EnableAllChannels property</summary>
        public bool? EnableAllChannels { get; set; }
        /// <summary>The EnableAllDevices property</summary>
        public bool? EnableAllDevices { get; set; }
        /// <summary>The EnableAllFolders property</summary>
        public bool? EnableAllFolders { get; set; }
        /// <summary>The EnableAudioPlaybackTranscoding property</summary>
        public bool? EnableAudioPlaybackTranscoding { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance can manage collections.</summary>
        public bool? EnableCollectionManagement { get; set; }
        /// <summary>The EnableContentDeletion property</summary>
        public bool? EnableContentDeletion { get; set; }
        /// <summary>The EnableContentDeletionFromFolders property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? EnableContentDeletionFromFolders { get; set; }
#nullable restore
#else
        public List<string> EnableContentDeletionFromFolders { get; set; }
#endif
        /// <summary>The EnableContentDownloading property</summary>
        public bool? EnableContentDownloading { get; set; }
        /// <summary>The EnabledChannels property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? EnabledChannels { get; set; }
#nullable restore
#else
        public List<Guid?> EnabledChannels { get; set; }
#endif
        /// <summary>The EnabledDevices property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? EnabledDevices { get; set; }
#nullable restore
#else
        public List<string> EnabledDevices { get; set; }
#endif
        /// <summary>The EnabledFolders property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? EnabledFolders { get; set; }
#nullable restore
#else
        public List<Guid?> EnabledFolders { get; set; }
#endif
        /// <summary>The EnableLiveTvAccess property</summary>
        public bool? EnableLiveTvAccess { get; set; }
        /// <summary>The EnableLiveTvManagement property</summary>
        public bool? EnableLiveTvManagement { get; set; }
        /// <summary>Gets or sets a value indicating whether this user can manage lyrics.</summary>
        public bool? EnableLyricManagement { get; set; }
        /// <summary>The EnableMediaConversion property</summary>
        public bool? EnableMediaConversion { get; set; }
        /// <summary>The EnableMediaPlayback property</summary>
        public bool? EnableMediaPlayback { get; set; }
        /// <summary>The EnablePlaybackRemuxing property</summary>
        public bool? EnablePlaybackRemuxing { get; set; }
        /// <summary>The EnablePublicSharing property</summary>
        public bool? EnablePublicSharing { get; set; }
        /// <summary>The EnableRemoteAccess property</summary>
        public bool? EnableRemoteAccess { get; set; }
        /// <summary>The EnableRemoteControlOfOtherUsers property</summary>
        public bool? EnableRemoteControlOfOtherUsers { get; set; }
        /// <summary>The EnableSharedDeviceControl property</summary>
        public bool? EnableSharedDeviceControl { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance can manage subtitles.</summary>
        public bool? EnableSubtitleManagement { get; set; }
        /// <summary>Gets or sets a value indicating whether [enable synchronize].</summary>
        public bool? EnableSyncTranscoding { get; set; }
        /// <summary>The EnableUserPreferenceAccess property</summary>
        public bool? EnableUserPreferenceAccess { get; set; }
        /// <summary>The EnableVideoPlaybackTranscoding property</summary>
        public bool? EnableVideoPlaybackTranscoding { get; set; }
        /// <summary>The ForceRemoteSourceTranscoding property</summary>
        public bool? ForceRemoteSourceTranscoding { get; set; }
        /// <summary>The InvalidLoginAttemptCount property</summary>
        public int? InvalidLoginAttemptCount { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is administrator.</summary>
        public bool? IsAdministrator { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is disabled.</summary>
        public bool? IsDisabled { get; set; }
        /// <summary>Gets or sets a value indicating whether this instance is hidden.</summary>
        public bool? IsHidden { get; set; }
        /// <summary>The LoginAttemptsBeforeLockout property</summary>
        public int? LoginAttemptsBeforeLockout { get; set; }
        /// <summary>The MaxActiveSessions property</summary>
        public int? MaxActiveSessions { get; set; }
        /// <summary>Gets or sets the max parental rating.</summary>
        public int? MaxParentalRating { get; set; }
        /// <summary>The PasswordResetProviderId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PasswordResetProviderId { get; set; }
#nullable restore
#else
        public string PasswordResetProviderId { get; set; }
#endif
        /// <summary>The RemoteClientBitrateLimit property</summary>
        public int? RemoteClientBitrateLimit { get; set; }

		[JsonConverter(typeof(JsonStringEnumConverter<UserPolicy_SyncPlayAccess>))]
        /// <summary>Enum SyncPlayUserAccessType.</summary>
        public global::Jellyfin.Client.Models.UserPolicy_SyncPlayAccess? SyncPlayAccess { get; set; }
       
    }
}
#pragma warning restore CS0618
