// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class UserConfiguration.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserConfiguration 
    {
        /// <summary>Gets or sets the audio language preference.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AudioLanguagePreference { get; set; }
#nullable restore
#else
        public string AudioLanguagePreference { get; set; }
#endif
        /// <summary>Gets or sets the id of the selected cast receiver.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CastReceiverId { get; set; }
#nullable restore
#else
        public string CastReceiverId { get; set; }
#endif
        /// <summary>The DisplayCollectionsView property</summary>
        public bool? DisplayCollectionsView { get; set; }
        /// <summary>The DisplayMissingEpisodes property</summary>
        public bool? DisplayMissingEpisodes { get; set; }
        /// <summary>The EnableLocalPassword property</summary>
        public bool? EnableLocalPassword { get; set; }
        /// <summary>The EnableNextEpisodeAutoPlay property</summary>
        public bool? EnableNextEpisodeAutoPlay { get; set; }
        /// <summary>The GroupedFolders property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? GroupedFolders { get; set; }
#nullable restore
#else
        public List<Guid?> GroupedFolders { get; set; }
#endif
        /// <summary>The HidePlayedInLatest property</summary>
        public bool? HidePlayedInLatest { get; set; }
        /// <summary>The LatestItemsExcludes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? LatestItemsExcludes { get; set; }
#nullable restore
#else
        public List<Guid?> LatestItemsExcludes { get; set; }
#endif
        /// <summary>The MyMediaExcludes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? MyMediaExcludes { get; set; }
#nullable restore
#else
        public List<Guid?> MyMediaExcludes { get; set; }
#endif
        /// <summary>The OrderedViews property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? OrderedViews { get; set; }
#nullable restore
#else
        public List<Guid?> OrderedViews { get; set; }
#endif
        /// <summary>Gets or sets a value indicating whether [play default audio track].</summary>
        public bool? PlayDefaultAudioTrack { get; set; }
        /// <summary>The RememberAudioSelections property</summary>
        public bool? RememberAudioSelections { get; set; }
        /// <summary>The RememberSubtitleSelections property</summary>
        public bool? RememberSubtitleSelections { get; set; }
        /// <summary>Gets or sets the subtitle language preference.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubtitleLanguagePreference { get; set; }
#nullable restore
#else
        public string SubtitleLanguagePreference { get; set; }
#endif
		[JsonConverter(typeof(JsonStringEnumConverter<UserConfiguration_SubtitleMode>))]
        /// <summary>An enum representing a subtitle playback mode.</summary>
        public global::Jellyfin.Client.Models.UserConfiguration_SubtitleMode? SubtitleMode { get; set; }
        
    }
}
#pragma warning restore CS0618
