// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>An enum representing a subtitle playback mode.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UserConfiguration_SubtitleMode
    {
        [JsonStringEnumMemberName("Default")]

        Default,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Always")]

        Always,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("OnlyForced")]

        OnlyForced,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("None")]

        None,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Smart")]

        Smart,
        #pragma warning restore CS1591
    }
}
