// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Class UtcTimeResponse.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UtcTimeResponse 
    {
        /// <summary>Gets the UTC time when request has been received.</summary>
        public DateTimeOffset? RequestReceptionTime { get; set; }
        /// <summary>Gets the UTC time when response has been sent.</summary>
        public DateTimeOffset? ResponseTransmissionTime { get; set; }
       
    }
}
#pragma warning restore CS0618
