// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Validate path object.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ValidatePathDto 
    {
        /// <summary>Gets or sets is path file.</summary>
        public bool? IsFile { get; set; }
        /// <summary>Gets or sets the path.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>Gets or sets a value indicating whether validate if path is writable.</summary>
        public bool? ValidateWritable { get; set; }
      
    }
}
#pragma warning restore CS0618
