// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Enum VideoType.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VideoType
    {
        [JsonStringEnumMemberName("VideoFile")]

        VideoFile,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Iso")]

        Iso,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("Dvd")]

        Dvd,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("BluRay")]

        BluRay,
        #pragma warning restore CS1591
    }
}
