// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>Gets or sets the type of the collection.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VirtualFolderInfo_CollectionType
    {
        [JsonStringEnumMemberName("movies")]

        Movies,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("tvshows")]

        Tvshows,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("music")]

        Music,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("musicvideos")]

        Musicvideos,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("homevideos")]

        Homevideos,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("boxsets")]

        Boxsets,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("books")]

        Books,
        #pragma warning restore CS1591
        [JsonStringEnumMemberName("mixed")]

        Mixed,
        #pragma warning restore CS1591
    }
}
