// <auto-generated/>
#pragma warning disable CS0618


using System.Collections.Generic;
using System.IO;
using System;
namespace Jellyfin.Client.Models
{
    /// <summary>
    /// Used to hold information about a user&apos;s list of configured virtual folders.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VirtualFolderInfo 
    {
        /// <summary>Gets or sets the type of the collection.</summary>
        public global::Jellyfin.Client.Models.VirtualFolderInfo_CollectionType? CollectionType { get; set; }
        /// <summary>Gets or sets the item identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ItemId { get; set; }
#nullable restore
#else
        public string ItemId { get; set; }
#endif
        /// <summary>The LibraryOptions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Jellyfin.Client.Models.LibraryOptions? LibraryOptions { get; set; }
#nullable restore
#else
        public global::Jellyfin.Client.Models.LibraryOptions LibraryOptions { get; set; }
#endif
        /// <summary>Gets or sets the locations.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Locations { get; set; }
#nullable restore
#else
        public List<string> Locations { get; set; }
#endif
        /// <summary>Gets or sets the name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Gets or sets the primary image item identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrimaryImageItemId { get; set; }
#nullable restore
#else
        public string PrimaryImageItemId { get; set; }
#endif
        /// <summary>The RefreshProgress property</summary>
        public double? RefreshProgress { get; set; }
        /// <summary>The RefreshStatus property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RefreshStatus { get; set; }
#nullable restore
#else
        public string RefreshStatus { get; set; }
#endif
    }
}
#pragma warning restore CS0618
